import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
import os
import uuid
from datetime import datetime, timezone

questions_data = [
  {"question": "A 25-year-old male is brought to the ER after a motorcycle accident. He is unconscious with a GCS of 7. His right pupil is dilated and non-reactive. What is the most likely diagnosis?", "option_a": "Diffuse axonal injury", "option_b": "Epidural hematoma with uncal herniation", "option_c": "Concussion", "option_d": "Basilar skull fracture", "correct_answer": "B", "explanation": "Unilateral pupil dilation (blown pupil) indicates ipsilateral uncal herniation compressing CN III, commonly seen with expanding epidural or subdural hematomas."},
  {"question": "A 40-year-old male presents with a stab wound to the left chest. He is hypotensive, has distended neck veins, and muffled heart sounds. What is the most immediate life-saving intervention?", "option_a": "Needle decompression", "option_b": "Pericardiocentesis", "option_c": "Tube thoracostomy", "option_d": "Emergency thoracotomy", "correct_answer": "B", "explanation": "The clinical triad of hypotension, JVD, and muffled heart sounds (Beck's Triad) suggests cardiac tamponade, requiring immediate decompression."},
  {"question": "Which of the following is the most sensitive finding for a tension pneumothorax?", "option_a": "Tracheal deviation", "option_b": "Hyperresonance to percussion and absent breath sounds", "option_c": "Ipsilateral lung collapse on X-ray", "option_d": "Subcutaneous emphysema", "correct_answer": "B", "explanation": "Tension pneumothorax is a clinical diagnosis characterized by respiratory distress, absent breath sounds, and hyperresonance. Tracheal deviation is a late and often absent sign."},
  {"question": "An adult patient suffered partial-thickness burns to the entire right arm and the entire anterior chest/abdomen. Using the Rule of Nines, what is the estimated Body Surface Area (BSA) burned?", "option_a": "18%", "option_b": "27%", "option_c": "36%", "option_d": "45%", "correct_answer": "B", "explanation": "The entire arm is 9% and the anterior trunk (chest and abdomen) is 18%. 9 + 18 = 27%."},
  {"question": "What is the preferred site for needle decompression of a tension pneumothorax in an adult according to ATLS 10th edition guidelines?", "option_a": "2nd intercostal space, mid-clavicular line", "option_b": "5th intercostal space, anterior axillary line", "option_c": "4th intercostal space, mid-axillary line", "option_d": "Between the 1st and 2nd ribs", "correct_answer": "B", "explanation": "Current ATLS guidelines prefer the 5th intercostal space at the anterior axillary line due to higher success rates in varying chest wall thicknesses."},
  {"question": "A patient is brought in after a motor vehicle accident. He is awake but confused. He opens his eyes to pain and withdraws from painful stimuli. What is his GCS score?", "option_a": "8", "option_b": "9", "option_c": "10", "option_d": "11", "correct_answer": "C", "explanation": "Eyes: 2 (to pain), Verbal: 4 (confused), Motor: 4 (withdraws). Total = 10."},
  {"question": "A 65-year-old male presents with sudden onset of tearing chest pain radiating to the back. His BP is 180/100 in the right arm and 130/70 in the left arm. What is the most likely diagnosis?", "option_a": "Myocardial infarction", "option_b": "Aortic dissection", "option_c": "Pulmonary embolism", "option_d": "Esophageal rupture", "correct_answer": "B", "explanation": "Sudden tearing pain and a significant blood pressure discrepancy between arms are classic for acute aortic dissection."},
  {"question": "Which of the following rhythms is considered shockable during cardiac arrest management?", "option_a": "Asystole", "option_b": "Pulseless Electrical Activity (PEA)", "option_c": "Pulseless Ventricular Tachycardia", "option_d": "Sinus Bradycardia", "correct_answer": "C", "explanation": "The shockable rhythms are Ventricular Fibrillation (VF) and Pulseless Ventricular Tachycardia (pVT)."},
  {"question": "A 22-year-old female presents with acute shortness of breath and wheezing. She is unable to speak in full sentences. What is the first-line medication?", "option_a": "Intravenous steroids", "option_b": "Inhaled Albuterol (Salbutamol)", "option_c": "Oral Theophylline", "option_d": "Magnesium sulfate", "correct_answer": "B", "explanation": "Short-acting beta-agonists (SABA) like Albuterol are the first-line treatment for acute asthma exacerbations."},
  {"question": "In the setting of a traumatic brain injury, what is the goal for Mean Arterial Pressure (MAP) to maintain cerebral perfusion?", "option_a": "At least 60 mmHg", "option_b": "At least 80 mmHg", "option_c": "At least 100 mmHg", "option_d": "MAP is not used; only systolic BP matters", "correct_answer": "B", "explanation": "Maintaining a MAP of at least 80 mmHg (or Systolic > 100-110 depending on age) is vital to ensure adequate Cerebral Perfusion Pressure (CPP)."},
  {"question": "A patient presents with tachycardia, hypotension, and warm, flushed skin. Which type of shock is most likely?", "option_a": "Hypovolemic", "option_b": "Cardiogenic", "option_c": "Septic (Distributive)", "option_d": "Obstructive", "correct_answer": "C", "explanation": "Early septic shock often presents with peripheral vasodilation (warm shock), unlike the cold, clammy skin of hypovolemic or cardiogenic shock."},
  {"question": "What is the definitive treatment for a patient with an unstable flail chest and respiratory failure?", "option_a": "Chest tube insertion", "option_b": "Intubation and mechanical ventilation", "option_c": "Taping the chest wall", "option_d": "Incentive spirometry", "correct_answer": "B", "explanation": "While pain control is vital, patients with flail chest and respiratory failure require positive pressure ventilation to stabilize the segment and improve oxygenation."},
  {"question": "A 55-year-old female presents with crushing chest pain and ST elevation in leads II, III, and aVF. Which wall of the heart is affected?", "option_a": "Anterior", "option_b": "Inferior", "option_c": "Lateral", "option_d": "Septal", "correct_answer": "B", "explanation": "Leads II, III, and aVF look at the inferior wall of the heart, usually supplied by the Right Coronary Artery (RCA)."},
  {"question": "Which of the following is an absolute contraindication to thrombolytic therapy in acute ischemic stroke?", "option_a": "Age > 80", "option_b": "Blood pressure of 170/90", "option_c": "Intracranial hemorrhage on non-contrast CT", "option_d": "Blood glucose of 200 mg/dL", "correct_answer": "C", "explanation": "The presence of any blood on the initial CT scan is an absolute contraindication to thrombolytics due to the risk of worsening hemorrhage."},
  {"question": "A patient with suspected opioid overdose is found with a respiratory rate of 4. What is the most appropriate initial management?", "option_a": "Immediate intubation", "option_b": "Bag-valve-mask ventilation and Naloxone", "option_c": "Gastric lavage", "option_d": "IV fluids and observation", "correct_answer": "B", "explanation": "Supporting ventilation while administering Naloxone is the standard approach to opioid-induced respiratory depression."},
  {"question": "Which electrolyte abnormality is most commonly associated with Digoxin toxicity?", "option_a": "Hypernatremia", "option_b": "Hypokalemia", "option_c": "Hypercalcemia", "option_d": "Hypomagnesemia", "correct_answer": "B", "explanation": "Hypokalemia (low potassium) sensitizes the heart to digoxin and significantly increases the risk of toxicity."},
  {"question": "A 70-year-old male with a history of hypertension presents with sudden onset of focal weakness and slurred speech. Symptoms started 2 hours ago. CT head is negative for hemorrhage. What is the next step?", "option_a": "Start Aspirin 325mg", "option_b": "Evaluate for tPA (Alteplase) eligibility", "option_c": "Perform a lumbar puncture", "option_d": "Discharge with follow-up", "correct_answer": "B", "explanation": "Since the symptoms started within the 3-4.5 hour window and the CT is negative for blood, the patient should be assessed for fibrinolytic therapy."},
  {"question": "What is the most common cause of death in the first hour after a major burn injury?", "option_a": "Infection", "option_b": "Airway compromise and inhalation injury", "option_c": "Hypovolemic shock", "option_d": "Renal failure", "correct_answer": "B", "explanation": "Early burn mortality is usually due to airway obstruction from edema or inhalation injury/carbon monoxide poisoning."},
  {"question": "A 30-year-old male is brought to the ER with a suspected C-spine injury. He is hypotensive (BP 80/40) and bradycardic (HR 50). His skin is warm. What is the most likely diagnosis?", "option_a": "Hypovolemic shock", "option_b": "Neurogenic shock", "option_c": "Spinal shock", "option_d": "Anaphylactic shock", "correct_answer": "B", "explanation": "Neurogenic shock, caused by loss of sympathetic tone, is characterized by the unique combination of hypotension and bradycardia with warm skin."},
  {"question": "Which of the following is a sign of Basilar Skull Fracture?", "option_a": "Muffled heart sounds", "option_b": "Battle sign (retroauricular ecchymosis)", "option_c": "Pulsus paradoxus", "option_d": "Tracheal deviation", "correct_answer": "B", "explanation": "Signs of a basilar skull fracture include Battle sign, Raccoon eyes, and CSF rhinorrhea/otorrhea."},
  {"question": "What is the Golden Hour in trauma?", "option_a": "The time it takes to get to the hospital", "option_b": "The period after injury when prompt treatment has the highest chance of preventing death", "option_c": "The hour after surgery", "option_d": "The hour before a cardiac arrest", "correct_answer": "B", "explanation": "The Golden Hour refers to the critical window where rapid trauma stabilization and surgical intervention can significantly improve survival outcomes."},
  {"question": "A patient with COPD presents with sudden onset of unilateral chest pain and worsening dyspnea. Breath sounds are absent on the right. What is the most likely diagnosis?", "option_a": "Pneumonia", "option_b": "Spontaneous pneumothorax", "option_c": "Pulmonary embolism", "option_d": "Myocardial infarction", "correct_answer": "B", "explanation": "Rupture of bullae in COPD patients can lead to secondary spontaneous pneumothorax."},
  {"question": "In the management of STEMI, what is the goal for door-to-balloon time in a facility with PCI capabilities?", "option_a": "60 minutes", "option_b": "90 minutes", "option_c": "120 minutes", "option_d": "30 minutes", "correct_answer": "B", "explanation": "The standard quality metric for Primary PCI in STEMI is a door-to-balloon time of 90 minutes or less."},
  {"question": "A patient is brought to the ER with a snake bite. There is significant local swelling and bruising. What is the most important treatment step?", "option_a": "Apply a tourniquet", "option_b": "Incise the wound and suction the venom", "option_c": "Administer antivenom", "option_d": "Apply ice pack to the site", "correct_answer": "C", "explanation": "Antivenom is the only definitive treatment for significant envenomation. Tourniquets and suction are contraindicated."},
  {"question": "A 12-year-old child presents with a barking cough and inspiratory stridor. What is the most likely diagnosis?", "option_a": "Epiglottitis", "option_b": "Croup (Laryngotracheobronchitis)", "option_c": "Foreign body aspiration", "option_d": "Asthma", "correct_answer": "B", "explanation": "Croup classically presents with a seal-like barking cough and stridor in young children, usually due to parainfluenza virus."},
  {"question": "Which of the following is the hallmark of heat stroke compared to heat exhaustion?", "option_a": "Excessive sweating", "option_b": "Altered mental status", "option_c": "Muscle cramps", "option_d": "Temperature of 38C", "correct_answer": "B", "explanation": "Heat stroke is a medical emergency defined by hyperthermia (usually >40C) and neurological dysfunction (confusion, seizures, or coma)."},
  {"question": "A 28-year-old female presents with severe lower abdominal pain and vaginal spotting. Her last menstrual period was 7 weeks ago. She is tachycardic and hypotensive. Diagnosis?", "option_a": "Appendicitis", "option_b": "Ruptured ectopic pregnancy", "option_c": "Pelvic Inflammatory Disease", "option_d": "Ovarian cyst rupture", "correct_answer": "B", "explanation": "In any woman of childbearing age with abdominal pain and shock, a ruptured ectopic pregnancy must be ruled out immediately."},
  {"question": "What is the initial fluid of choice for resuscitation in a trauma patient with hemorrhagic shock?", "option_a": "D5W", "option_b": "Isotonic crystalloid (Normal Saline or Lactated Ringer's)", "option_c": "Albumin 5%", "option_d": "Fresh Frozen Plasma", "correct_answer": "B", "explanation": "Isotonic crystalloids are the first-line fluids for initial volume expansion in trauma, though blood products are prioritized in massive hemorrhage."},
  {"question": "Which of the following describes the S in the SAMPLE history tool used in the ER?", "option_a": "Surgery", "option_b": "Signs and Symptoms", "option_c": "Social history", "option_d": "Strokes", "correct_answer": "B", "explanation": "SAMPLE stands for: Signs/Symptoms, Allergies, Medications, Past medical history, Last meal, Events leading to injury."},
  {"question": "A 45-year-old male with a history of alcoholism presents with hematemesis. He has spider angiomata and caput medusae. What is the most likely source of bleeding?", "option_a": "Mallory-Weiss tear", "option_b": "Esophageal varices", "option_c": "Peptic ulcer", "option_d": "Gastric cancer", "correct_answer": "B", "explanation": "In a patient with signs of cirrhosis and portal hypertension, esophageal varices are the most common cause of massive upper GI bleeding."},
  {"question": "Which of the following is part of Cushing's Triad, indicating increased intracranial pressure?", "option_a": "Hypotension, tachycardia, irregular breathing", "option_b": "Hypertension, bradycardia, irregular breathing", "option_c": "Hypertension, tachycardia, fever", "option_d": "Hypotension, bradycardia, pinpoint pupils", "correct_answer": "B", "explanation": "Cushing's triad consists of hypertension (usually with wide pulse pressure), bradycardia, and abnormal respiratory patterns."},
  {"question": "A patient presents with sudden severe epigastric pain that hit like a thunderbolt. The abdomen is board-like and rigid. What is the most likely diagnosis?", "option_a": "Acute pancreatitis", "option_b": "Perforated peptic ulcer", "option_c": "Cholecystitis", "option_d": "Renal colic", "correct_answer": "B", "explanation": "Sudden, excruciating pain and peritonitis (rigid abdomen) suggest a perforated viscus, often a peptic ulcer."},
  {"question": "Which medication is used to prevent seizures in a patient with Eclampsia?", "option_a": "Phenytoin", "option_b": "Magnesium sulfate", "option_c": "Diazepam", "option_d": "Levetiracetam", "correct_answer": "B", "explanation": "Magnesium sulfate is the drug of choice for seizure prophylaxis and treatment in preeclampsia/eclampsia."},
  {"question": "What is the most effective way to rewarm a patient with severe hypothermia (Temp < 28C) and cardiac arrest?", "option_a": "Warm blankets", "option_b": "Heated IV fluids and warm humidified oxygen", "option_c": "Extracorporeal membrane oxygenation (ECMO) or Bypass", "option_d": "Warm water immersion", "correct_answer": "C", "explanation": "Severe hypothermia with cardiac arrest requires active internal rewarming using extracorporeal methods (ECMO/Bypass)."},
  {"question": "A patient presents after a fire with singed nasal hairs, soot in the mouth, and hoarseness. What is the most critical next step?", "option_a": "Obtain an arterial blood gas", "option_b": "Perform a chest X-ray", "option_c": "Early endotracheal intubation", "option_d": "Start IV fluids", "correct_answer": "C", "explanation": "Signs of inhalation injury (singed hairs, soot, hoarseness) predict rapid airway edema, requiring early prophylactic intubation."},
  {"question": "Which of the following is the definitive treatment for a patient in Ventricular Fibrillation?", "option_a": "Epinephrine IV", "option_b": "Amiodarone IV", "option_c": "Defibrillation", "option_d": "Synchronized cardioversion", "correct_answer": "C", "explanation": "Defibrillation is the only treatment that can terminate ventricular fibrillation."},
  {"question": "A 50-year-old male presents with sudden onset of unilateral eye pain, redness, and a fixed, mid-dilated pupil. He sees halos around lights. Diagnosis?", "option_a": "Conjunctivitis", "option_b": "Acute angle-closure glaucoma", "option_c": "Iritis", "option_d": "Corneal abrasion", "correct_answer": "B", "explanation": "Acute angle-closure glaucoma is an ophthalmologic emergency characterized by severe pain, halos, and a non-reactive pupil."},
  {"question": "What is the most common cause of non-traumatic cardiac arrest in adults?", "option_a": "Pulmonary embolism", "option_b": "Coronary Artery Disease", "option_c": "Drug overdose", "option_d": "Sepsis", "correct_answer": "B", "explanation": "The majority of adult cardiac arrests are caused by underlying ischemic heart disease (CAD)."},
  {"question": "In a patient with a pelvic fracture and urethral bleeding, what is the most appropriate next step in management?", "option_a": "Insert a Foley catheter", "option_b": "Perform a retrograde urethrogram", "option_c": "Perform a CT abdomen", "option_d": "Wait for the patient to void", "correct_answer": "B", "explanation": "If urethral injury is suspected (blood at meatus, high-riding prostate), a retrograde urethrogram must be performed before attempting catheterization."},
  {"question": "Which lead on an ECG shows ST elevation in a Lateral wall Myocardial Infarction?", "option_a": "V1-V2", "option_b": "I, aVL, V5, V6", "option_c": "II, III, aVF", "option_d": "V3-V4", "correct_answer": "B", "explanation": "Leads I, aVL, V5, and V6 correspond to the lateral wall of the left ventricle."},
  {"question": "A child presents with high fever, drooling, and sitting in a tripod position. What is the most likely diagnosis?", "option_a": "Croup", "option_b": "Epiglottitis", "option_c": "Bronchiolitis", "option_d": "Pneumonia", "correct_answer": "B", "explanation": "Epiglottitis is a pediatric emergency characterized by high fever, drooling, and the tripod position (now rare due to HiB vaccine)."},
  {"question": "What is the primary objective of the Secondary Survey in trauma?", "option_a": "To identify life-threatening injuries", "option_b": "To perform a head-to-toe examination to identify all injuries", "option_c": "To start IV fluids", "option_d": "To intubate the patient", "correct_answer": "B", "explanation": "The secondary survey is a systematic, head-to-toe examination performed only after the primary survey (ABCDEs) is complete and the patient is stabilized."},
  {"question": "Which of the following is an early sign of local anesthetic systemic toxicity (LAST)?", "option_a": "Seizures", "option_b": "Perioral numbness and metallic taste", "option_c": "Cardiac arrest", "option_d": "Respiratory failure", "correct_answer": "B", "explanation": "Neurological symptoms like a metallic taste, tinnitus, and perioral numbness often precede major CNS or cardiac toxicity in LAST."},
  {"question": "In a patient with suspected tension pneumothorax, when should you obtain a chest X-ray?", "option_a": "Immediately upon arrival", "option_b": "After needle decompression and chest tube insertion", "option_c": "Before decompression to confirm the diagnosis", "option_d": "Only if the patient is stable", "correct_answer": "B", "explanation": "Tension pneumothorax is a clinical diagnosis. Decompression should never be delayed for imaging."},
  {"question": "Which of the following findings on an ECG is diagnostic of hyperkalemia?", "option_a": "U-waves", "option_b": "Peaked T-waves", "option_c": "Shortened PR interval", "option_d": "ST elevation in all leads", "correct_answer": "B", "explanation": "Tall, peaked (tented) T-waves are the earliest ECG manifestation of hyperkalemia."},
  {"question": "A patient is brought in after an electrical injury. What is the most important initial test to monitor for complications?", "option_a": "Head CT", "option_b": "ECG", "option_c": "Abdominal Ultrasound", "option_d": "Chest X-ray", "correct_answer": "B", "explanation": "Electrical injuries can cause lethal arrhythmias; an ECG is essential to monitor cardiac rhythm."},
  {"question": "Which of the following is a classic clinical finding in pulmonary embolism?", "option_a": "Bradycardia", "option_b": "Tachycardia and sudden onset dyspnea", "option_c": "Hypothermia", "option_d": "Localized wheezing", "correct_answer": "B", "explanation": "Tachycardia and acute dyspnea are the most common (though non-specific) clinical findings in PE."},
  {"question": "What is the first step in the management of a patient with an open pneumothorax (sucking chest wound)?", "option_a": "Insert a chest tube", "option_b": "Apply an occlusive dressing taped on three sides", "option_c": "Perform immediate surgery", "option_d": "Intubate the patient", "correct_answer": "B", "explanation": "A three-sided dressing acts as a one-way valve, allowing air to escape but not enter, preventing a tension pneumothorax."},
  {"question": "A 19-year-old male presents with sudden onset of severe right-sided scrotal pain. The cremasteric reflex is absent. What is the most likely diagnosis?", "option_a": "Epididymitis", "option_b": "Testicular torsion", "option_c": "Hydrocele", "option_d": "Inguinal hernia", "correct_answer": "B", "explanation": "Testicular torsion is a surgical emergency; the absence of the cremasteric reflex is highly suggestive of the diagnosis."},
  {"question": "Which of the following is the preferred medication for rate control in a stable patient with Atrial Fibrillation and no heart failure?", "option_a": "Amiodarone", "option_b": "Diltiazem or Metoprolol", "option_c": "Adenosine", "option_d": "Atropine", "correct_answer": "B", "explanation": "Calcium channel blockers (like Diltiazem) or Beta-blockers (like Metoprolol) are first-line for rate control in stable AFib."}
]

COURSE_ID = "NVU_MD_Y4_S2_C39"

async def main():
    client = AsyncIOMotorClient(os.environ["MONGO_URL"])
    db = client[os.environ["DB_NAME"]]
    
    current_count = await db.mcq_questions.count_documents({"course_id": COURSE_ID})
    print(f"Current questions: {current_count}")
    
    questions_to_insert = []
    for q in questions_data:
        question_doc = {
            "question_id": f"q_{uuid.uuid4().hex[:12]}",
            "course_id": COURSE_ID,
            "question": q["question"],
            "option_a": q["option_a"],
            "option_b": q["option_b"],
            "option_c": q["option_c"],
            "option_d": q["option_d"],
            "correct_answer": q["correct_answer"],
            "explanation": q["explanation"],
            "created_at": datetime.now(timezone.utc).isoformat()
        }
        questions_to_insert.append(question_doc)
    
    result = await db.mcq_questions.insert_many(questions_to_insert)
    print(f"Inserted: {len(result.inserted_ids)} questions")
    
    new_count = await db.mcq_questions.count_documents({"course_id": COURSE_ID})
    await db.courses.update_one(
        {"external_id": COURSE_ID},
        {"$set": {"mcq_count": new_count, "mcq_verified": True}}
    )
    print(f"Total now: {new_count}")

if __name__ == "__main__":
    asyncio.run(main())
