import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
import os
import uuid
from datetime import datetime, timezone

questions_data = [
  {"question": "A 45-year-old male with a history of intravenous drug use presents with chronic fatigue. Labs show elevated ALT and AST, and positive HCV RNA. What is the most important long-term complication to monitor for in this patient?", "option_a": "Pancreatic cancer", "option_b": "Hepatocellular carcinoma", "option_c": "Splenic infarction", "option_d": "Chronic cholecystitis", "correct_answer": "B", "explanation": "Chronic Hepatitis C infection is a leading cause of cirrhosis and significantly increases the risk of developing hepatocellular carcinoma (HCC)."},
  {"question": "A 60-year-old female presents with acute onset of severe epigastric pain radiating to the back. Serum lipase is 1200 U/L (Normal < 160). CT scan shows peripancreatic fluid collection. What is the most common cause of this condition in non-alcoholics?", "option_a": "Hypertriglyceridemia", "option_b": "Gallstones (Choledocholithiasis)", "option_c": "Viral infection (Mumps)", "option_d": "Autoimmune destruction", "correct_answer": "B", "explanation": "Gallstones are the leading cause of acute pancreatitis, as they can obstruct the common bile duct or the pancreatic duct."},
  {"question": "A 30-year-old male presents with chronic diarrhea, weight loss, and iron deficiency anemia. A biopsy of the distal duodenum shows villous atrophy and crypt hyperplasia. What is the next best step?", "option_a": "Start a gluten-free diet", "option_b": "Test for anti-tissue transglutaminase (tTG) antibodies", "option_c": "Perform a colonoscopy", "option_d": "Administer broad-spectrum antibiotics", "correct_answer": "B", "explanation": "Villous atrophy is highly suggestive of Celiac Disease. Serological testing for anti-tTG IgA is the preferred non-invasive confirmatory test."},
  {"question": "A 52-year-old patient with long-standing Type 2 Diabetes presents with early satiety and vomiting of undigested food several hours after meals. What is the most likely diagnosis?", "option_a": "Peptic ulcer disease", "option_b": "Diabetic gastroparesis", "option_c": "Gastric cancer", "option_d": "Small bowel obstruction", "correct_answer": "B", "explanation": "Autonomic neuropathy in long-term diabetics can affect the vagus nerve, leading to delayed gastric emptying (gastroparesis)."},
  {"question": "A 70-year-old smoker presents with hemoptysis and a weight loss of 10kg. A chest X-ray reveals a central mass. Labs show a serum sodium of 122 mEq/L and low serum osmolality. What is the most likely diagnosis?", "option_a": "Squamous cell carcinoma causing hypercalcemia", "option_b": "Small cell lung cancer causing SIADH", "option_c": "Adenocarcinoma causing pleural effusion", "option_d": "Large cell carcinoma", "correct_answer": "B", "explanation": "Small cell lung cancer (SCLC) is a neuroendocrine tumor that often produces paraneoplastic syndromes like the Syndrome of Inappropriate Antidiuretic Hormone (SIADH)."},
  {"question": "A 40-year-old female presents with progressive dyspnea. Physical exam reveals a loud P2 and a right ventricular heave. Echocardiogram shows a mean pulmonary artery pressure of 35 mmHg. Diagnosis?", "option_a": "Aortic Stenosis", "option_b": "Pulmonary Hypertension", "option_c": "Mitral Valve Prolapse", "option_d": "Left Ventricular Failure", "correct_answer": "B", "explanation": "Pulmonary hypertension is defined as a mean pulmonary artery pressure >20 mmHg at rest."},
  {"question": "A 65-year-old male presents with sudden onset of painless gross hematuria. He has a history of working in a chemical factory. What is the most likely diagnosis?", "option_a": "Nephrolithiasis", "option_b": "Bladder Cancer", "option_c": "Glomerulonephritis", "option_d": "Prostatitis", "correct_answer": "B", "explanation": "Painless gross hematuria in an elderly patient is a classic presentation of transitional cell carcinoma (bladder cancer), especially with chemical exposure history."},
  {"question": "A patient with Chronic Kidney Disease presents with persistent itching (pruritus) and bone pain. Labs show High PTH, High Phosphate, and Low Calcium. What is the term for this condition?", "option_a": "Primary hyperparathyroidism", "option_b": "Secondary hyperparathyroidism", "option_c": "Tertiary hyperparathyroidism", "option_d": "Hypoparathyroidism", "correct_answer": "B", "explanation": "In CKD, phosphate retention and low calcitriol trigger chronic parathyroid stimulation, known as secondary hyperparathyroidism."},
  {"question": "A 35-year-old female presents with palpitations and tremor. Her TSH is very low, and Free T4 is high. Radioiodine uptake scan shows diffuse increased uptake. Diagnosis?", "option_a": "Toxic Multinodular Goiter", "option_b": "Graves Disease", "option_c": "Subacute Thyroiditis", "option_d": "Toxic Adenoma", "correct_answer": "B", "explanation": "Diffuse uptake on a thyroid scan indicates that the entire gland is overactive, which is characteristic of Graves disease."},
  {"question": "A 50-year-old male with hypertension presents with a blood pressure of 220/120 mmHg and blurred vision. Fundoscopy shows papilledema. What is the most appropriate management?", "option_a": "Oral Lisinopril and discharge", "option_b": "Intravenous nitroprusside or labetalol and ICU admission", "option_c": "Vigorous IV fluid resuscitation", "option_d": "Oral Furosemide", "correct_answer": "B", "explanation": "Hypertensive emergency (BP >180/120 with end-organ damage like papilledema) requires parenteral antihypertensives to carefully lower BP."},
  {"question": "Which of the following physical exam findings is most specific for Cardiac Tamponade?", "option_a": "S3 heart sound", "option_b": "Pulsus paradoxus", "option_c": "Holosystolic murmur", "option_d": "Opening snap", "correct_answer": "B", "explanation": "Pulsus paradoxus (a drop in systolic BP >10 mmHg during inspiration) is a hallmark of cardiac tamponade."},
  {"question": "A 45-year-old woman with a history of Hashimoto's thyroiditis presents with a rapid enlargement of her thyroid gland and new onset of hoarseness. What is the most feared complication?", "option_a": "Thyroid storm", "option_b": "Thyroid lymphoma", "option_c": "Graves disease", "option_d": "Iodine deficiency", "correct_answer": "B", "explanation": "Patients with Hashimoto's thyroiditis have a significantly increased risk of developing primary thyroid lymphoma."},
  {"question": "A patient presents with recurrent peptic ulcers that are refractory to PPI therapy. Labs show a fasting gastrin level >1000 pg/mL. Diagnosis?", "option_a": "H. pylori infection", "option_b": "Zollinger-Ellison Syndrome", "option_c": "Celiac disease", "option_d": "Gastric adenocarcinoma", "correct_answer": "B", "explanation": "Zollinger-Ellison Syndrome is caused by a gastrin-secreting tumor (gastrinoma), leading to severe, refractory peptic ulcer disease."},
  {"question": "In a patient with Acute Respiratory Distress Syndrome (ARDS), what is the primary pathophysiological change?", "option_a": "Increased left atrial pressure", "option_b": "Increased permeability of the alveolar-capillary membrane", "option_c": "Bronchospasm", "option_d": "Pulmonary embolism", "correct_answer": "B", "explanation": "ARDS is characterized by non-cardiogenic pulmonary edema caused by diffuse alveolar damage and leaky capillaries."},
  {"question": "A 65-year-old male presents with fatigue and a feeling of fullness in the left upper quadrant. Exam reveals massive splenomegaly. CBC shows WBC 150,000 with a full spectrum of myeloid cells and 1% blasts. Diagnosis?", "option_a": "Acute Myeloid Leukemia", "option_b": "Chronic Myeloid Leukemia (CML)", "option_c": "Polycythemia Vera", "option_d": "Aplastic Anemia", "correct_answer": "B", "explanation": "CML is characterized by a high WBC count with a left shift (all stages of maturation) and is associated with the BCR-ABL translocation (Philadelphia chromosome)."},
  {"question": "A 55-year-old male presents with polyuria and thirst. Labs show Na 148 (High), serum osmolality 310 (High), and urine osmolality 100 (Low). After ADH administration, urine osmolality remains 100. Diagnosis?", "option_a": "Central Diabetes Insipidus", "option_b": "Nephrogenic Diabetes Insipidus", "option_c": "SIADH", "option_d": "Primary polydipsia", "correct_answer": "B", "explanation": "Failure of urine to concentrate after ADH administration indicates that the kidneys are resistant to ADH, which is Nephrogenic DI."},
  {"question": "What is the most common cause of Primary Hyperaldosteronism?", "option_a": "Adrenal carcinoma", "option_b": "Adrenal adenoma (Conn's Syndrome)", "option_c": "Pituitary adenoma", "option_d": "Exogenous steroids", "correct_answer": "B", "explanation": "Conn's Syndrome (a unilateral adrenal adenoma) is a classic cause of primary hyperaldosteronism, presenting with hypertension and hypokalemia."},
  {"question": "A 40-year-old female presents with obesity, moon face, and purple striae on her abdomen. Low-dose dexamethasone fails to suppress cortisol, but high-dose dexamethasone does suppress it. What is the most likely source of excess cortisol?", "option_a": "Adrenal tumor", "option_b": "Pituitary adenoma (Cushing's Disease)", "option_c": "Small cell lung cancer", "option_d": "Exogenous steroids", "correct_answer": "B", "explanation": "Suppression with high-dose dexamethasone is characteristic of a pituitary source (Cushing's Disease). Adrenal and ectopic sources do not suppress."},
  {"question": "Which heart murmur is heard as a blowing holosystolic murmur at the lower left sternal border that increases with inspiration?", "option_a": "Mitral Regurgitation", "option_b": "Tricuspid Regurgitation", "option_c": "Aortic Regurgitation", "option_d": "Ventricular Septal Defect", "correct_answer": "B", "explanation": "Tricuspid regurgitation is holosystolic and classically increases with inspiration (Carvallo's sign) due to increased venous return to the right heart."},
  {"question": "A patient with cirrhosis presents with increased confusion and a flapping tremor of the hands (asterixis). What is the primary toxin responsible?", "option_a": "Bilirubin", "option_b": "Ammonia", "option_c": "Urea", "option_d": "Ethanol", "correct_answer": "B", "explanation": "Hepatic encephalopathy is caused by the liver's failure to clear neurotoxins, primarily ammonia, from the portal circulation."},
  {"question": "A 25-year-old male presents with hemoptysis and kidney failure. A lung biopsy shows linear IgG deposits along the glomerular basement membrane. Diagnosis?", "option_a": "Wegener's Granulomatosis", "option_b": "Goodpasture Syndrome", "option_c": "Systemic Lupus Erythematosus", "option_d": "Post-streptococcal glomerulonephritis", "correct_answer": "B", "explanation": "Goodpasture Syndrome is characterized by anti-GBM antibodies that produce a linear immunofluorescence pattern on biopsy."},
  {"question": "Which of the following is the most sensitive marker for diagnosing an acute exacerbation of Chronic Obstructive Pulmonary Disease (COPD)?", "option_a": "Chest X-ray", "option_b": "Increased dyspnea, sputum volume, or sputum purulence", "option_c": "Fever > 39C", "option_d": "Metabolic alkalosis on ABG", "correct_answer": "B", "explanation": "The diagnosis of a COPD exacerbation is clinical, based on a change in baseline respiratory symptoms."},
  {"question": "A 50-year-old male with long-standing Hypertension presents with sudden onset of severe, tearing chest pain radiating to the back. A Chest X-ray shows a widened mediastinum. Diagnosis?", "option_a": "Myocardial Infarction", "option_b": "Aortic Dissection", "option_c": "Pulmonary Embolism", "option_d": "Esophageal Perforation", "correct_answer": "B", "explanation": "Aortic dissection is a life-threatening emergency often presenting with tearing pain and a widened mediastinum on X-ray."},
  {"question": "A patient with Chronic Heart Failure is started on an ACE inhibitor. Which of the following is a common, non-allergic side effect related to bradykinin accumulation?", "option_a": "Peripheral edema", "option_b": "Dry, non-productive cough", "option_c": "Hypokalemia", "option_d": "Constipation", "correct_answer": "B", "explanation": "ACE inhibitors prevent the breakdown of bradykinin, which can irritate the lungs and cause a persistent dry cough in about 10% of patients."},
  {"question": "A 30-year-old woman presents with symmetrical small joint pain and stiffness that improves with activity. Lab tests show a positive Anti-CCP antibody. Diagnosis?", "option_a": "Osteoarthritis", "option_b": "Rheumatoid Arthritis", "option_c": "Gouty Arthritis", "option_d": "Systemic Lupus Erythematosus", "correct_answer": "B", "explanation": "Anti-cyclic citrullinated peptide (anti-CCP) antibodies are highly specific for Rheumatoid Arthritis."},
  {"question": "In a patient with Acute Kidney Injury, a Fractional Excretion of Sodium (FeNa) < 1% most likely suggests:", "option_a": "Acute Tubular Necrosis", "option_b": "Prerenal Azotemia", "option_c": "Postrenal obstruction", "option_d": "Drug-induced interstitial nephritis", "correct_answer": "B", "explanation": "A low FeNa (<1%) indicates that the kidneys are still able to concentrate urine and conserve sodium, typical of prerenal states (hypoperfusion)."},
  {"question": "A 45-year-old male presents with jaundice and a positive HBsAg and HBeAg. This indicates:", "option_a": "Immunity due to vaccination", "option_b": "Acute or chronic infection with high infectivity", "option_c": "Resolved infection", "option_d": "Chronic infection with low infectivity", "correct_answer": "B", "explanation": "HBeAg is a marker of active viral replication and high transmissibility in Hepatitis B infection."},
  {"question": "Which of the following is the hallmark of restrictive lung disease on Pulmonary Function Tests (PFTs)?", "option_a": "FEV1/FVC < 0.7", "option_b": "Decreased Total Lung Capacity (TLC)", "option_c": "Increased lung compliance", "option_d": "Normal Residual Volume", "correct_answer": "B", "explanation": "Restrictive lung diseases (like fibrosis or chest wall deformity) are defined by reduced TLC."},
  {"question": "A 60-year-old male presents with severe pain in his great toe that started overnight. Exam shows redness and swelling of the 1st MTP joint. What is the most likely finding on synovial fluid analysis?", "option_a": "Rhomboid-shaped positively birefringent crystals", "option_b": "Needle-shaped negatively birefringent crystals", "option_c": "Gram-positive cocci in clusters", "option_d": "High glucose levels", "correct_answer": "B", "explanation": "These are monosodium urate crystals, diagnostic of Gout."},
  {"question": "What is the primary pharmacological treatment for a patient with a documented Pulmonary Embolism who is hemodynamically stable?", "option_a": "Aspirin", "option_b": "Anticoagulation (e.g., Heparin or DOACs)", "option_c": "Thrombolytics (e.g., tPA)", "option_d": "Emergent embolectomy", "correct_answer": "B", "explanation": "Anticoagulation prevents clot propagation and further emboli; thrombolytics are reserved for unstable patients (massive PE)."},
  {"question": "A patient presents with tearing chest pain and a BP of 180/110. An ECG shows left ventricular hypertrophy but no ST elevations. Which class of medication is contraindicated if an aortic dissection is suspected?", "option_a": "Beta-blockers", "option_b": "Thrombolytics", "option_c": "Vasodilators", "option_d": "Morphine", "correct_answer": "B", "explanation": "Thrombolytics would be catastrophic in an aortic dissection as they would prevent clotting and exacerbate the bleeding into the false lumen."},
  {"question": "Which heart valve is most commonly affected in Acute Rheumatic Fever?", "option_a": "Aortic valve", "option_b": "Mitral valve", "option_c": "Tricuspid valve", "option_d": "Pulmonic valve", "correct_answer": "B", "explanation": "The mitral valve is involved in nearly all cases of rheumatic carditis, followed by the aortic valve."},
  {"question": "A 50-year-old male presents with a sudden worst headache of my life. A CT scan is negative. What is the next best step?", "option_a": "Repeat the CT in 24 hours", "option_b": "Lumbar puncture", "option_c": "Discharge with analgesics", "option_d": "MRI of the brain", "correct_answer": "B", "explanation": "If clinical suspicion of Subarachnoid Hemorrhage is high and the CT is negative, a lumbar puncture must be performed to look for xanthochromia or RBCs."},
  {"question": "Which of the following is a classic clinical finding in primary hyperparathyroidism?", "option_a": "Hypocalcemia", "option_b": "Hypercalcemia and Kidney stones", "option_c": "Hyperphosphatemia", "option_d": "Shortened QT interval", "correct_answer": "B", "explanation": "Classic triad: Stones (renal), Bones (pain), Groans (abdominal pain), and Psychic moans (mental changes)."},
  {"question": "A 40-year-old female presents with fatigue and jaundice. Exam shows a palpable, non-tender gallbladder (Courvoisier sign). This most likely suggests:", "option_a": "Cholelithiasis", "option_b": "Pancreatic head cancer", "option_c": "Acute Hepatitis A", "option_d": "Primary Biliary Cirrhosis", "correct_answer": "B", "explanation": "A palpable, non-tender gallbladder in a jaundiced patient is highly suggestive of malignant obstruction of the common bile duct, such as pancreatic cancer."},
  {"question": "A patient with long-term hypertension presents with sudden onset of unilateral weakness and slurred speech. CT shows a small, deep infarction in the internal capsule. This is an example of a:", "option_a": "Cardioembolic stroke", "option_b": "Lacunar stroke", "option_c": "Subarachnoid hemorrhage", "option_d": "Watershed infarct", "correct_answer": "B", "explanation": "Lacunar strokes are small vessel infarctions caused by lipohyalinosis of small penetrating arteries, strongly associated with chronic hypertension."},
  {"question": "What is the clinical triad of Wernicke's Encephalopathy?", "option_a": "Fever, jaundice, abdominal pain", "option_b": "Confusion, Ophthalmoplegia, Ataxia", "option_c": "Headache, vomiting, papilledema", "option_d": "Dementia, gait instability, incontinence", "correct_answer": "B", "explanation": "Caused by Thiamine (B1) deficiency, typically in chronic alcohol use."},
  {"question": "A 70-year-old male with a history of COPD presents with increased sputum volume and green-colored sputum. Which of the following is the most likely pathogen?", "option_a": "Mycoplasma pneumoniae", "option_b": "Haemophilus influenzae", "option_c": "Legionella pneumophila", "option_d": "Pneumocystis jirovecii", "correct_answer": "B", "explanation": "H. influenzae, S. pneumoniae, and M. catarrhalis are the most common causes of bacterial COPD exacerbations."},
  {"question": "In a patient with Acute Myocardial Infarction, which of the following is the most common cause of death in the first few hours?", "option_a": "Heart failure", "option_b": "Ventricular Arrhythmias", "option_c": "Papillary muscle rupture", "option_d": "Ventricular septal rupture", "correct_answer": "B", "explanation": "Ventricular fibrillation is the most common cause of early pre-hospital mortality in MI."},
  {"question": "A 55-year-old male presents with persistent epigastric pain and dark, tarry stools (melena). What is the most likely source of bleeding?", "option_a": "Ascending colon", "option_b": "Upper Gastrointestinal tract (e.g., Stomach or Duodenum)", "option_c": "Hemorrhoids", "option_d": "Diverticulosis", "correct_answer": "B", "explanation": "Melena results from the digestion of blood in the upper GI tract; bright red blood (hematochezia) usually indicates a lower GI source."}
]

COURSE_ID = "NVU_MD_Y3_S1_C24"

async def main():
    client = AsyncIOMotorClient(os.environ["MONGO_URL"])
    db = client[os.environ["DB_NAME"]]
    
    current_count = await db.mcq_questions.count_documents({"course_id": COURSE_ID})
    print(f"Current questions: {current_count}")
    
    questions_to_insert = []
    for q in questions_data:
        question_doc = {
            "question_id": f"q_{uuid.uuid4().hex[:12]}",
            "course_id": COURSE_ID,
            "question": q["question"],
            "option_a": q["option_a"],
            "option_b": q["option_b"],
            "option_c": q["option_c"],
            "option_d": q["option_d"],
            "correct_answer": q["correct_answer"],
            "explanation": q["explanation"],
            "created_at": datetime.now(timezone.utc).isoformat()
        }
        questions_to_insert.append(question_doc)
    
    result = await db.mcq_questions.insert_many(questions_to_insert)
    print(f"Inserted: {len(result.inserted_ids)} questions")
    
    new_count = await db.mcq_questions.count_documents({"course_id": COURSE_ID})
    await db.courses.update_one(
        {"external_id": COURSE_ID},
        {"$set": {"mcq_count": new_count, "mcq_verified": True}}
    )
    print(f"Total now: {new_count}")

if __name__ == "__main__":
    asyncio.run(main())
