import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
import os
import uuid
from datetime import datetime, timezone

questions_data = [
  {"question": "A 55-year-old male presents with sudden onset of substernal chest pain radiating to the left arm. ECG shows ST-segment elevation in leads V2-V4. Which coronary artery is most likely occluded?", "option_a": "Right coronary artery", "option_b": "Left anterior descending artery", "option_c": "Left circumflex artery", "option_d": "Posterior descending artery", "correct_answer": "B", "explanation": "Leads V2-V4 correspond to the anterior wall of the heart, which is primarily supplied by the Left Anterior Descending (LAD) artery."},
  {"question": "A 68-year-old patient with Chronic Heart Failure presents with increased edema and dyspnea. Physical exam reveals a displaced apical pulse and an S3 gallop. What is the physiological correlate of the S3 heart sound?", "option_a": "Atrial contraction against a stiff ventricle", "option_b": "Rapid ventricular filling into a dilated, compliant ventricle", "option_c": "Closure of the mitral and tricuspid valves", "option_d": "Delayed closure of the pulmonic valve", "correct_answer": "B", "explanation": "An S3 gallop occurs during the early phase of diastole and is associated with rapid ventricular filling, typical in eccentric remodeling/systolic heart failure."},
  {"question": "A 72-year-old female presents with palpitations and lightheadedness. Her ECG shows an irregularly irregular rhythm without discernible P-waves. What is the most important initial goal in managing this patient?", "option_a": "Immediate electrical cardioversion", "option_b": "Rate control and thromboembolism risk assessment", "option_c": "Administration of high-dose aspirin", "option_d": "Cardiac catheterization", "correct_answer": "B", "explanation": "In stable Atrial Fibrillation, the focus is on heart rate control and determining the need for anticoagulation based on scores like CHA2DS2-VASc."},
  {"question": "A 45-year-old male is diagnosed with Hypertension. He has a history of Type 2 Diabetes and microalbuminuria. Which of the following is the preferred first-line antihypertensive?", "option_a": "Amlodipine", "option_b": "Lisinopril", "option_c": "Hydrochlorothiazide", "option_d": "Metoprolol", "correct_answer": "B", "explanation": "ACE inhibitors like Lisinopril (or ARBs) are preferred in diabetic patients because of their renoprotective effects and ability to reduce proteinuria."},
  {"question": "A 60-year-old smoker presents with productive cough for 4 months and exertional dyspnea. Spirometry shows an FEV1/FVC ratio of 0.62. What is the hallmark of Chronic Bronchitis?", "option_a": "Permanent enlargement of airspaces distal to terminal bronchioles", "option_b": "Hypertrophy of mucus-secreting glands in the bronchi", "option_c": "Eosinophilic infiltration of the bronchial wall", "option_d": "Granulomatous inflammation of the lung parenchyma", "correct_answer": "B", "explanation": "Chronic bronchitis is defined clinically by a productive cough and pathologically by the Reid index increase (glandular hypertrophy)."},
  {"question": "A 30-year-old male presents with pleuritic chest pain and dyspnea 10 days after a long-haul flight. HR is 110 bpm, O2 saturation is 91%. What is the most appropriate initial diagnostic test?", "option_a": "D-dimer assay", "option_b": "CT Pulmonary Angiogram", "option_c": "Chest X-ray", "option_d": "Ventilation-Perfusion (V/Q) scan", "correct_answer": "B", "explanation": "In a patient with high clinical suspicion for Pulmonary Embolism (PE), CTPA is the gold standard for diagnosis."},
  {"question": "A 25-year-old female presents with wheezing and shortness of breath that worsens at night and during exercise. Which of the following findings on spirometry supports a diagnosis of Asthma?", "option_a": "Fixed airway obstruction", "option_b": "Improvement in FEV1 by >12% after bronchodilator inhalation", "option_c": "Decreased Total Lung Capacity (TLC)", "option_d": "Increased Diffusing Capacity for Carbon Monoxide (DLCO)", "correct_answer": "B", "explanation": "Reversibility of airway obstruction following a bronchodilator is a key diagnostic feature of Asthma."},
  {"question": "An 80-year-old man presents with syncope and exertional chest pain. On auscultation, there is a harsh systolic crescendo-decrescendo murmur at the right upper sternal border radiating to the carotids. What is the diagnosis?", "option_a": "Mitral Regurgitation", "option_b": "Aortic Stenosis", "option_c": "Tricuspid Stenosis", "option_d": "Hypertrophic Cardiomyopathy", "correct_answer": "B", "explanation": "The triad of syncope, angina, and dyspnea (SAD) with a systolic murmur radiating to the carotids is classic for Aortic Stenosis."},
  {"question": "A 50-year-old patient with a history of alcohol use disorder presents with hematemesis. Exam shows spider angiomata and caput medusae. What is the most likely cause of bleeding?", "option_a": "Mallory-Weiss tear", "option_b": "Esophageal varices", "option_c": "Peptic ulcer disease", "option_d": "Gastric adenocarcinoma", "correct_answer": "B", "explanation": "The physical signs indicate liver cirrhosis and portal hypertension, which lead to esophageal varices, a common cause of life-threatening upper GI bleeding."},
  {"question": "A 40-year-old female presents with fatigue and jaundice. Labs reveal elevated ALT and AST (10x upper limit) and positive anti-smooth muscle antibodies. What is the treatment of choice?", "option_a": "Ribavirin", "option_b": "Corticosteroids", "option_c": "Interferon-alpha", "option_d": "Ursodeoxycholic acid", "correct_answer": "B", "explanation": "The presence of anti-smooth muscle antibodies (ASMA) and hepatitis suggests Autoimmune Hepatitis, which is treated with immunosuppressants like prednisone."},
  {"question": "A 58-year-old male with long-standing GERD undergoes endoscopy. Biopsy shows columnar epithelium with goblet cells in the distal esophagus. What is this condition called?", "option_a": "Squamous cell carcinoma", "option_b": "Barrett's Esophagus", "option_c": "Achalasia", "option_d": "Zenker's diverticulum", "correct_answer": "B", "explanation": "Barrett's esophagus is intestinal metaplasia (replacement of squamous with columnar cells) due to chronic acid reflux, increasing adenocarcinoma risk."},
  {"question": "A 35-year-old male presents with bloody diarrhea and abdominal pain. Colonoscopy shows continuous mucosal inflammation starting from the rectum. What is the most likely diagnosis?", "option_a": "Crohn's Disease", "option_b": "Ulcerative Colitis", "option_c": "Celiac Disease", "option_d": "Diverticulitis", "correct_answer": "B", "explanation": "Ulcerative Colitis typically involves continuous inflammation starting from the rectum and moving proximally, limited to the mucosa."},
  {"question": "A 20-year-old male presents with periorbital edema and dark 'cola-colored' urine two weeks after a sore throat. Lab shows elevated ASO titer and low C3. What is the diagnosis?", "option_a": "Minimal Change Disease", "option_b": "Post-Streptococcal Glomerulonephritis", "option_c": "IgA Nephropathy", "option_d": "Goodpasture Syndrome", "correct_answer": "B", "explanation": "PSGN presents with nephritic syndrome (hematuria, hypertension, edema) approximately 1-3 weeks after a group A strep infection."},
  {"question": "A 65-year-old male with CKD Stage 4 presents with weakness. ECG shows peaked T-waves and widened QRS complexes. What is the most immediate treatment?", "option_a": "Hemodialysis", "option_b": "Intravenous Calcium Gluconate", "option_c": "Sodium Polystyrene Sulfonate", "option_d": "Intravenous Furosemide", "correct_answer": "B", "explanation": "Peaked T-waves indicate severe hyperkalemia. IV Calcium gluconate stabilizes the cardiac membrane to prevent arrhythmias while other measures lower K+."},
  {"question": "A 45-year-old obese female presents with polyuria and thirst. Her fasting blood glucose is 140 mg/dL on two occasions. What is the next step in management?", "option_a": "Immediate start of Insulin", "option_b": "Lifestyle modification and Metformin", "option_c": "Repeat glucose testing in 6 months", "option_d": "Start Sulfonylureas", "correct_answer": "B", "explanation": "A fasting glucose >126 mg/dL is diagnostic for Diabetes. Metformin and lifestyle changes are the standard first-line therapy for Type 2 Diabetes."},
  {"question": "A 30-year-old female presents with heat intolerance, weight loss, and bulging eyes (exophthalmos). TSH is suppressed, and free T4 is elevated. What is the underlying mechanism?", "option_a": "Destruction of thyroid follicles", "option_b": "TSH receptor antibodies stimulating the gland", "option_c": "Iodine deficiency", "option_d": "Pituitary adenoma secreting TSH", "correct_answer": "B", "explanation": "Graves' disease is caused by Thyroid-Stimulating Immunoglobulins (TSI) that bind to and activate the TSH receptor."},
  {"question": "A 60-year-old man presents with bone pain and normocytic anemia. Serum protein electrophoresis shows an M-spike. Bone marrow biopsy shows 15% plasma cells. Diagnosis?", "option_a": "Acute Myeloid Leukemia", "option_b": "Multiple Myeloma", "option_c": "Chronic Lymphocytic Leukemia", "option_d": "Waldenstrom Macroglobulinemia", "correct_answer": "B", "explanation": "Multiple Myeloma is a plasma cell dyscrasia characterized by monoclonal (M) protein spike, CRAB features (calcium, renal, anemia, bone pain)."},
  {"question": "A patient presents with sudden severe epigastric pain radiating to the back and vomiting. Amylase and Lipase are 4x the upper limit. What is the most common cause of this condition?", "option_a": "Alcohol and Gallstones", "option_b": "Medications and Infections", "option_c": "Trauma and Surgery", "option_d": "Hypertriglyceridemia", "correct_answer": "A", "explanation": "Gallstones and heavy alcohol use account for the majority of Acute Pancreatitis cases."},
  {"question": "A 65-year-old male with a history of HTN and smoking presents with sudden tearing chest pain radiating to his back. Blood pressure is 180/100 in the right arm and 140/80 in the left arm. Diagnosis?", "option_a": "Acute Myocardial Infarction", "option_b": "Aortic Dissection", "option_c": "Pneumothorax", "option_d": "Esophageal rupture", "correct_answer": "B", "explanation": "Sudden 'tearing' pain and asymmetric blood pressure readings between arms are classic indicators of an Aortic Dissection."},
  {"question": "Which of the following is a classic clinical finding in Iron Deficiency Anemia?", "option_a": "Hypersegmented neutrophils", "option_b": "Hypochromic microcytic RBCs", "option_c": "Target cells", "option_d": "Schistocytes", "correct_answer": "B", "explanation": "Iron deficiency leads to reduced hemoglobin synthesis, resulting in small (microcytic) and pale (hypochromic) red blood cells."},
  {"question": "A 70-year-old male presents with dullness to percussion and decreased breath sounds at the right lung base. Thoracentesis shows fluid with high protein and LDH. Diagnosis?", "option_a": "Transudative effusion (e.g., Heart failure)", "option_b": "Exudative effusion (e.g., Pneumonia/Malignancy)", "option_c": "Normal finding in elderly", "option_d": "Atelectasis", "correct_answer": "B", "explanation": "Light's criteria define an exudate by pleural fluid protein/serum protein > 0.5 or pleural LDH/serum LDH > 0.6."},
  {"question": "A patient with Vitamin B12 deficiency presents with anemia and neurological symptoms. Which lab value is most likely to be elevated?", "option_a": "Ferritin", "option_b": "Methylmalonic acid", "option_c": "Haptoglobin", "option_d": "Transferrin", "correct_answer": "B", "explanation": "B12 is a cofactor for converting methylmalonyl-CoA to succinyl-CoA. In deficiency, Methylmalonic Acid (MMA) levels rise."},
  {"question": "What is the most common cause of Community-Acquired Pneumonia?", "option_a": "Staphylococcus aureus", "option_b": "Streptococcus pneumoniae", "option_c": "Mycoplasma pneumoniae", "option_d": "Klebsiella pneumoniae", "correct_answer": "B", "explanation": "Streptococcus pneumoniae (pneumococcus) remains the most common bacterial trigger for CAP globally."},
  {"question": "A 50-year-old male with chronic HTN presents with sudden severe headache and vomiting. CT shows blood in the subarachnoid space. What is the most likely cause?", "option_a": "Epidural hematoma", "option_b": "Ruptured berry aneurysm", "option_c": "Ischemic stroke", "option_d": "Venous sinus thrombosis", "correct_answer": "B", "explanation": "Subarachnoid hemorrhage (SAH) is most frequently caused by a ruptured saccular (berry) aneurysm, often presenting as a 'thunderclap' headache."},
  {"question": "In a patient with Acute Kidney Injury, the presence of 'muddy brown' granular casts in the urine sediment is characteristic of:", "option_a": "Acute Glomerulonephritis", "option_b": "Acute Tubular Necrosis (ATN)", "option_c": "Prerenal azotemia", "option_d": "Interstitial nephritis", "correct_answer": "B", "explanation": "Muddy brown casts are pathognomonic for ATN, representing necrotic tubular epithelial cells."},
  {"question": "A 62-year-old male with COPD presents with worsening edema and jugular venous distention. What is the term for right-sided heart failure caused by lung disease?", "option_a": "Congestive Heart Failure", "option_b": "Cor Pulmonale", "option_c": "Tetralogy of Fallot", "option_d": "Cardiomyopathy", "correct_answer": "B", "explanation": "Cor pulmonale is right ventricular hypertrophy and failure resulting from pulmonary hypertension due to chronic lung disease."},
  {"question": "Which heart valve is most commonly affected in IV drug users with Infective Endocarditis?", "option_a": "Mitral valve", "option_b": "Tricuspid valve", "option_c": "Aortic valve", "option_d": "Pulmonic valve", "correct_answer": "B", "explanation": "IV drug users are at high risk for right-sided endocarditis, specifically involving the tricuspid valve, often caused by S. aureus."},
  {"question": "A 55-year-old man presents with chronic fatigue and 'bronze' skin. Labs show high serum iron and saturation. What is the most likely diagnosis?", "option_a": "Wilson disease", "option_b": "Hereditary Hemochromatosis", "option_c": "Secondary syphilis", "option_d": "Addison disease", "correct_answer": "B", "explanation": "Hemochromatosis is an iron-overload disorder that can lead to cirrhosis, diabetes ('bronze diabetes'), and skin hyperpigmentation."},
  {"question": "Which of the following is a classic ECG finding in Acute Pericarditis?", "option_a": "Isolated ST-elevation in Lead II", "option_b": "Diffuse concave ST-elevation and PR-depression", "option_c": "Deep Q-waves", "option_d": "Large S-waves in Lead I", "correct_answer": "B", "explanation": "Acute pericarditis usually shows widespread ST elevation across most leads, accompanied by PR segment depression."},
  {"question": "A patient presents with facial puffiness and massive proteinuria (>3.5g/day). Biopsy shows effacement of podocyte foot processes. What is the likely diagnosis?", "option_a": "Nephritic syndrome", "option_b": "Minimal Change Disease", "option_c": "Polycystic Kidney Disease", "option_d": "Renal cell carcinoma", "correct_answer": "B", "explanation": "Minimal Change Disease is the most common cause of nephrotic syndrome in children and presents with podocyte effacement on electron microscopy."},
  {"question": "A 35-year-old woman presents with anxiety, tachycardia, and a painful thyroid gland after a viral illness. Diagnosis?", "option_a": "Hashimoto's thyroiditis", "option_b": "De Quervain's (Subacute) thyroiditis", "option_c": "Graves' disease", "option_d": "Thyroid cancer", "correct_answer": "B", "explanation": "Subacute thyroiditis is often post-viral and is characterized by a tender, painful thyroid with transient hyperthyroidism."},
  {"question": "A 60-year-old smoker presents with weight loss and a new cough. Lab reveals hypercalcemia. Which type of lung cancer is most associated with PTHrP production?", "option_a": "Small cell carcinoma", "option_b": "Squamous cell carcinoma", "option_c": "Adenocarcinoma", "option_d": "Large cell carcinoma", "correct_answer": "B", "explanation": "Squamous cell carcinoma of the lung often produces parathyroid hormone-related protein (PTHrP), causing hypercalcemia."},
  {"question": "What is the most common cause of Cushing's Syndrome?", "option_a": "Adrenal adenoma", "option_b": "Exogenous corticosteroid use", "option_c": "Pituitary adenoma", "option_d": "Ectopic ACTH production", "correct_answer": "B", "explanation": "While 'Cushing's Disease' is specifically a pituitary adenoma, 'Cushing's Syndrome' (the clinical state) is most often caused by iatrogenic steroid use."},
  {"question": "A 65-year-old female presents with bone pain and pathological fractures. Lab shows high Calcium and low Phosphate. Diagnosis?", "option_a": "Hypoparathyroidism", "option_b": "Primary Hyperparathyroidism", "option_c": "Vitamin D deficiency", "option_d": "Osteoporosis", "correct_answer": "B", "explanation": "Primary hyperparathyroidism (often due to a parathyroid adenoma) leads to excessive PTH, raising serum calcium and lowering phosphate."},
  {"question": "Which electrolyte abnormality is a common side effect of Loop Diuretics (e.g., Furosemide)?", "option_a": "Hyperkalemia", "option_b": "Hypokalemia", "option_c": "Hypercalcemia", "option_d": "Hyponatremia", "correct_answer": "B", "explanation": "Loop diuretics inhibit K+ reabsorption in the thick ascending limb, leading to increased potassium excretion and hypokalemia."},
  {"question": "A 50-year-old patient with cirrhosis presents with abdominal distension. Fluid analysis shows a SAAG (Serum-Ascites Albumin Gradient) of 1.2. This indicates:", "option_a": "Tuberculosis", "option_b": "Portal Hypertension", "option_c": "Pancreatitis", "option_d": "Malignancy", "correct_answer": "B", "explanation": "A SAAG >= 1.1 g/dL is highly suggestive of portal hypertension as the cause of ascites."},
  {"question": "A 70-year-old male has an incidental finding of a high white cell count (50,000) with 90% small mature lymphocytes and 'smudge cells' on smear. Diagnosis?", "option_a": "Acute Lymphoblastic Leukemia", "option_b": "Chronic Lymphocytic Leukemia (CLL)", "option_c": "Infectious Mononucleosis", "option_d": "Hodgkin Lymphoma", "correct_answer": "B", "explanation": "CLL is a common leukemia in the elderly, characterized by mature-appearing but dysfunctional B-lymphocytes and smudge cells."},
  {"question": "A 30-year-old female with a history of DVT presents with recurrent miscarriages. Lab shows prolonged PTT that doesn't correct with mixing. Diagnosis?", "option_a": "Von Willebrand disease", "option_b": "Antiphospholipid Syndrome", "option_c": "Hemophilia A", "option_d": "Factor V Leiden", "correct_answer": "B", "explanation": "APS is characterized by arterial/venous thrombosis and pregnancy loss, often associated with a 'lupus anticoagulant' that prolongs PTT."},
  {"question": "In a patient with suspected Acute Myocardial Infarction, which cardiac biomarker rises earliest?", "option_a": "Troponin I", "option_b": "Myoglobin", "option_c": "CK-MB", "option_d": "LDH", "correct_answer": "B", "explanation": "Myoglobin is the earliest marker to rise (1-3 hours), though it is not specific for cardiac muscle."},
  {"question": "What is the clinical triad of Addison's disease (Primary Adrenal Insufficiency)?", "option_a": "HTN, Hyperglycemia, Obesity", "option_b": "Hypotension, Hyponatremia, Hyperkalemia", "option_c": "Tachycardia, Tremor, Sweating", "option_d": "Edema, Proteinuria, Hypoalbuminemia", "correct_answer": "B", "explanation": "Loss of aldosterone leads to Na+ wasting (hyponatremia, hypotension) and K+ retention (hyperkalemia)."},
  {"question": "A 60-year-old smoker with sudden weight loss and hemoptysis has a central lung mass on CXR. Biopsy shows small round blue cells. Diagnosis?", "option_a": "Adenocarcinoma", "option_b": "Small Cell Lung Cancer", "option_c": "Squamous cell carcinoma", "option_d": "Mesothelioma", "correct_answer": "B", "explanation": "Small cell lung cancer is highly associated with smoking, central location, and neuroendocrine features."},
  {"question": "A patient with stable angina is prescribed Nitroglycerin. What is its primary mechanism for relieving chest pain?", "option_a": "Increasing heart rate", "option_b": "Venodilation reducing preload and oxygen demand", "option_c": "Systemic vasoconstriction", "option_d": "Inhibiting platelet aggregation", "correct_answer": "B", "explanation": "Nitrates cause systemic venodilation, which lowers venous return (preload) and reduces the work/oxygen consumption of the heart."},
  {"question": "A 50-year-old male presents with severe pain in his first metatarsophalangeal joint. Arthrocentesis shows needle-shaped negatively birefringent crystals. Diagnosis?", "option_a": "Pseudogout", "option_b": "Gout", "option_c": "Rheumatoid Arthritis", "option_d": "Septic arthritis", "correct_answer": "B", "explanation": "Monosodium urate crystals in gout are needle-shaped and negatively birefringent under polarized light."},
  {"question": "A 40-year-old male presents with polyuria and very dilute urine. Administration of desmopressin (ADH) results in a significant increase in urine osmolality. Diagnosis?", "option_a": "Nephrogenic Diabetes Insipidus", "option_b": "Central Diabetes Insipidus", "option_c": "Primary Polydipsia", "option_d": "SIADH", "correct_answer": "B", "explanation": "In central DI, there is a lack of ADH. Providing exogenous ADH (desmopressin) corrects the inability to concentrate urine."},
  {"question": "A patient with persistent epigastric pain has a urea breath test that is positive. Which organism is being tested for?", "option_a": "Escherichia coli", "option_b": "Helicobacter pylori", "option_c": "Salmonella typhi", "option_d": "Clostridium difficile", "correct_answer": "B", "explanation": "H. pylori produces urease, which converts urea to ammonia and CO2. This is the basis for the breath test."},
  {"question": "Which of the following is the most common cause of Chronic Kidney Disease in developed countries?", "option_a": "Polycystic Kidney Disease", "option_b": "Diabetes Mellitus", "option_c": "Chronic Glomerulonephritis", "option_d": "Autoimmune diseases", "correct_answer": "B", "explanation": "Diabetic nephropathy is the leading cause of end-stage renal disease (ESRD)."},
  {"question": "A patient with COPD presents with sudden onset of unilateral chest pain and absent breath sounds on the same side. Diagnosis?", "option_a": "Pneumonia", "option_b": "Spontaneous Pneumothorax", "option_c": "Pleural effusion", "option_d": "Pulmonary embolism", "correct_answer": "B", "explanation": "Patients with COPD can develop blebs that rupture, leading to a secondary spontaneous pneumothorax."},
  {"question": "Which of the following findings on endoscopy is most suggestive of Crohn's Disease?", "option_a": "Continuous inflammation and pseudopolyps", "option_b": "Skip lesions and cobblestoning", "option_c": "Loss of haustra (lead-pipe sign)", "option_d": "Crypt abscesses only", "correct_answer": "B", "explanation": "Crohn's is characterized by transmural inflammation, skip lesions (patchy areas), and a 'cobblestone' appearance of the mucosa."},
  {"question": "A 30-year-old male with HIV presents with a CD4 count of 150. Which prophylactic medication should be started to prevent Pneumocystis pneumonia?", "option_a": "Azithromycin", "option_b": "Trimethoprim-Sulfamethoxazole", "option_c": "Fluconazole", "option_d": "Acyclovir", "correct_answer": "B", "explanation": "TMP-SMX is the primary prophylaxis for PCP in immunocompromised patients with CD4 < 200."},
  {"question": "What is the primary diagnostic feature of Nephrotic Syndrome?", "option_a": "Hematuria and hypertension", "option_b": "Proteinuria > 3.5 g/24 hours", "option_c": "Elevated creatinine only", "option_d": "Red blood cell casts", "correct_answer": "B", "explanation": "Nephrotic syndrome is defined by massive proteinuria (>3.5g/day), hypoalbuminemia, and edema."}
]

COURSE_ID = "NVU_MD_Y3_S1_C24"

async def main():
    client = AsyncIOMotorClient(os.environ["MONGO_URL"])
    db = client[os.environ["DB_NAME"]]
    
    current_count = await db.mcq_questions.count_documents({"course_id": COURSE_ID})
    print(f"Current questions: {current_count}")
    
    questions_to_insert = []
    for q in questions_data:
        question_doc = {
            "question_id": f"q_{uuid.uuid4().hex[:12]}",
            "course_id": COURSE_ID,
            "question": q["question"],
            "option_a": q["option_a"],
            "option_b": q["option_b"],
            "option_c": q["option_c"],
            "option_d": q["option_d"],
            "correct_answer": q["correct_answer"],
            "explanation": q["explanation"],
            "created_at": datetime.now(timezone.utc).isoformat()
        }
        questions_to_insert.append(question_doc)
    
    result = await db.mcq_questions.insert_many(questions_to_insert)
    print(f"Inserted: {len(result.inserted_ids)} questions")
    
    new_count = await db.mcq_questions.count_documents({"course_id": COURSE_ID})
    await db.courses.update_one(
        {"external_id": COURSE_ID},
        {"$set": {"mcq_count": new_count, "mcq_verified": True}}
    )
    print(f"Total now: {new_count}")

if __name__ == "__main__":
    asyncio.run(main())
