import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
import os
import uuid
from datetime import datetime, timezone

questions_data = [
  {"question": "A 24-year-old Mediterranean male presents with mild fatigue. Labs show Hemoglobin of 10.5 g/dL, MCV of 65 fL (very low), and a normal RDW. Mentzer index (MCV/RBC) is <13. What is the most likely diagnosis?", "option_a": "Iron deficiency anemia", "option_b": "Beta-Thalassemia trait", "option_c": "Sideroblastic anemia", "option_d": "Anemia of chronic disease", "correct_answer": "B", "explanation": "A very low MCV with a normal RDW and a Mentzer index <13 in a patient of Mediterranean descent is highly suggestive of Thalassemia trait rather than iron deficiency."},
  {"question": "A 60-year-old male with long-standing Hypertension presents with sudden headache and blurred vision. His BP is 210/130 mmHg. Fundoscopy reveals bilateral papilledema. Which of the following is the most appropriate management?", "option_a": "Oral Nifedipine to rapidly lower BP", "option_b": "IV Labetalol with a goal to lower MAP by 20-25% over the first hour", "option_c": "Aggressive IV fluids", "option_d": "High-dose oral Furosemide", "correct_answer": "B", "explanation": "This is a hypertensive emergency (BP >180/120 with end-organ damage). Treatment requires IV medications (like Labetalol or Nicardipine) with a controlled reduction in mean arterial pressure (MAP) to prevent cerebral hypoperfusion."},
  {"question": "A 70-year-old male presents with bone pain, fatigue, and recurrent infections. Labs show hypercalcemia and a serum creatinine of 2.1 mg/dL. Serum protein electrophoresis shows a monoclonal (M) spike. What is the most likely diagnosis?", "option_a": "Primary Hyperparathyroidism", "option_b": "Multiple Myeloma", "option_c": "Chronic Lymphocytic Leukemia", "option_d": "Monoclonal Gammopathy of Undetermined Significance (MGUS)", "correct_answer": "B", "explanation": "The CRAB criteria (Calcium elevation, Renal insufficiency, Anemia, Bone lesions) combined with an M-spike are classic for Multiple Myeloma."},
  {"question": "A 45-year-old female presents with fatigue, weight gain, and cold intolerance. Lab results show TSH of 12 mU/L (High) and Free T4 of 0.6 ng/dL (Low). Which antibody is most commonly associated with this condition?", "option_a": "Thyroid-stimulating immunoglobulin (TSI)", "option_b": "Anti-thyroid peroxidase (anti-TPO) antibody", "option_c": "Anti-double stranded DNA (anti-dsDNA)", "option_d": "Anticentromere antibody", "correct_answer": "B", "explanation": "Elevated TSH and low T4 indicate primary hypothyroidism, most commonly Hashimoto's thyroiditis, which is associated with anti-TPO and anti-thyroglobulin antibodies."},
  {"question": "A patient with a history of cirrhosis presents with massive hematemesis. After stabilization, which of the following is the most appropriate pharmacological treatment to reduce portal pressure?", "option_a": "Propranolol", "option_b": "Octreotide", "option_c": "Vitamin K", "option_d": "Lactulose", "correct_answer": "B", "explanation": "In acute variceal bleeding, Octreotide (a somatostatin analog) is used to cause splanchnic vasoconstriction and reduce portal blood flow."},
  {"question": "A 62-year-old male with a 40-pack-year smoking history presents with progressive dyspnea and a chronic productive cough. Spirometry reveals an FEV1/FVC ratio of 0.55. What is the most likely diagnosis?", "option_a": "Asthma", "option_b": "COPD", "option_c": "Interstitial lung disease", "option_d": "Congestive heart failure", "correct_answer": "B", "explanation": "An FEV1/FVC ratio < 0.70 that is not fully reversible is the diagnostic hallmark of COPD, especially in a chronic smoker."},
  {"question": "Which of the following electrolyte abnormalities is a common side effect of Thiazide diuretics?", "option_a": "Hyperkalemia", "option_b": "Hypokalemia and Hypercalcemia", "option_c": "Hypocalcemia", "option_d": "Hypernatremia", "correct_answer": "B", "explanation": "Thiazides cause potassium wasting (hypokalemia) and increase calcium reabsorption in the distal tubule (hypercalcemia), unlike loop diuretics which cause hypocalcemia."},
  {"question": "A 55-year-old male presents with severe mid-epigastric pain radiating to the back, nausea, and vomiting. Labs show a Serum Lipase of 1500 U/L. Which of the following is the most likely etiology in a non-alcoholic patient?", "option_a": "Viral infection", "option_b": "Gallstones", "option_c": "Hypercalcemia", "option_d": "Autoimmune disease", "correct_answer": "B", "explanation": "Gallstones and alcohol are the two most common causes of acute pancreatitis. In non-alcoholics, gallstones should be the primary suspicion."},
  {"question": "A 30-year-old female presents with anxiety, palpitations, and heat intolerance. TSH is suppressed, and Free T4 is elevated. Radioiodine uptake shows diffuse increased uptake. What is the diagnosis?", "option_a": "Toxic Multinodular Goiter", "option_b": "Graves Disease", "option_c": "Subacute Thyroiditis", "option_d": "Toxic Adenoma", "correct_answer": "B", "explanation": "Diffuse increased uptake on a thyroid scan is the classic finding for Graves disease, caused by TSH-receptor antibodies."},
  {"question": "A patient with Chronic Kidney Disease (CKD) presents with a pericardial friction rub on examination. What is the next best step in management?", "option_a": "Start high-dose Aspirin", "option_b": "Immediate Hemodialysis", "option_c": "Administer Corticosteroids", "option_d": "Perform pericardiocentesis", "correct_answer": "B", "explanation": "Uremic pericarditis is an absolute indication for starting or increasing the frequency of hemodialysis."},
  {"question": "A 50-year-old male presents with sudden, sharp chest pain that is relieved by leaning forward. ECG shows diffuse ST-segment elevation and PR-segment depression. Diagnosis?", "option_a": "Acute Myocardial Infarction", "option_b": "Acute Pericarditis", "option_c": "Aortic Dissection", "option_d": "Pneumothorax", "correct_answer": "B", "explanation": "Positional chest pain combined with diffuse (rather than localized) ST-elevation and PR-depression is diagnostic of acute pericarditis."},
  {"question": "A 68-year-old female with AFib presents with acute, severe abdominal pain out of proportion to physical exam. Diagnosis?", "option_a": "Acute Cholecystitis", "option_b": "Acute Mesenteric Ischemia", "option_c": "Perforated Peptic Ulcer", "option_d": "Diverticulitis", "correct_answer": "B", "explanation": "Sudden onset of severe abdominal pain in a patient with an embolic risk factor (AFib) and a relatively normal physical exam is classic for acute mesenteric ischemia."},
  {"question": "Which of the following lab findings is most consistent with Primary Hyperparathyroidism?", "option_a": "Low Calcium, High PTH", "option_b": "High Calcium, High PTH, Low Phosphate", "option_c": "High Calcium, Low PTH", "option_d": "Low Calcium, Low PTH", "correct_answer": "B", "explanation": "Primary hyperparathyroidism leads to excessive PTH, which increases serum calcium and decreases phosphate through renal excretion."},
  {"question": "A 35-year-old male presents with bloody diarrhea, tenesmus, and lower abdominal pain. Colonoscopy shows continuous mucosal inflammation from the rectum to the splenic flexure. Diagnosis?", "option_a": "Crohn's Disease", "option_b": "Ulcerative Colitis", "option_c": "Infectious Colitis", "option_d": "Ischemic Colitis", "correct_answer": "B", "explanation": "Ulcerative Colitis involves continuous mucosal inflammation limited to the colon, always starting in the rectum."},
  {"question": "A 60-year-old male smoker with COPD presents with sudden onset of right-sided chest pain and dyspnea. Exam shows absent breath sounds on the right. Diagnosis?", "option_a": "Pneumonia", "option_b": "Secondary Spontaneous Pneumothorax", "option_c": "Pulmonary Embolism", "option_d": "Pleural Effusion", "correct_answer": "B", "explanation": "Secondary spontaneous pneumothorax occurs in patients with underlying lung disease (like COPD) due to rupture of bullae."},
  {"question": "In a patient with Type 1 Diabetes, which of the following is the diagnostic triad of Diabetic Ketoacidosis (DKA)?", "option_a": "Glucose >600, pH >7.3, No ketones", "option_b": "Glucose >250, pH <7.3, Positive ketones", "option_c": "Glucose >126, normal pH, Normal ketones", "option_d": "Glucose <50, pH <7.2, Positive ketones", "correct_answer": "B", "explanation": "DKA is defined by hyperglycemia (>250 mg/dL), metabolic acidosis (pH <7.3 or bicarbonate <18), and the presence of ketones in blood or urine."},
  {"question": "A 55-year-old female presents with fatigue and jaundice. Exam shows a palpable, non-tender gallbladder. What is the most likely diagnosis?", "option_a": "Cholelithiasis", "option_b": "Pancreatic cancer (head of pancreas)", "option_c": "Acute Hepatitis A", "option_d": "Primary Biliary Cirrhosis", "correct_answer": "B", "explanation": "Courvoisier's law: A palpable, non-tender gallbladder in a jaundiced patient suggests malignant obstruction of the common bile duct, most often from pancreatic cancer."},
  {"question": "A 40-year-old male presents with weight loss, polyuria, and blurred vision. Fasting glucose is 180 mg/dL. Which medication is first-line for this patient?", "option_a": "Insulin", "option_b": "Metformin", "option_c": "Glyburide", "option_d": "Sitagliptin", "correct_answer": "B", "explanation": "Metformin is the initial pharmacological therapy of choice for Type 2 Diabetes unless contraindicated (e.g., severe renal failure)."},
  {"question": "A patient with a history of DVT presents with sudden dyspnea and tachycardia. Which test is the most appropriate next step for definitive diagnosis?", "option_a": "Chest X-ray", "option_b": "CT Pulmonary Angiogram (CTPA)", "option_c": "D-dimer", "option_d": "ECG", "correct_answer": "B", "explanation": "In a patient with high clinical suspicion for Pulmonary Embolism, CTPA is the preferred imaging modality to confirm the diagnosis."},
  {"question": "A 70-year-old male has an incidental white blood cell count of 60,000. Smear shows mature lymphocytes and smudge cells. Diagnosis?", "option_a": "Acute Myeloid Leukemia", "option_b": "Chronic Lymphocytic Leukemia (CLL)", "option_c": "Chronic Myeloid Leukemia", "option_d": "Multiple Myeloma", "correct_answer": "B", "explanation": "CLL is characterized by a high count of mature-appearing lymphocytes and fragile smudge cells on the peripheral smear."},
  {"question": "What is the hallmark finding on biopsy in Crohn's Disease?", "option_a": "Crypt abscesses", "option_b": "Non-caseating granulomas", "option_c": "Pseudomembranes", "option_d": "Malignant transformation", "correct_answer": "B", "explanation": "Non-caseating granulomas are found in approximately 50% of Crohn's biopsies and help distinguish it from Ulcerative Colitis."},
  {"question": "A patient with suspected Primary Aldosteronism (Conn's Syndrome) presents with HTN and weakness. What are the expected lab values?", "option_a": "High Aldosterone, High Renin", "option_b": "High Aldosterone, Low Renin", "option_c": "Low Aldosterone, High Renin", "option_d": "Low Aldosterone, Low Renin", "correct_answer": "B", "explanation": "Primary hyperaldosteronism involves autonomous aldosterone production, which suppresses renin through negative feedback from increased blood pressure and sodium."},
  {"question": "A 55-year-old male smoker with a persistent cough presents with facial swelling and dilated neck veins. Diagnosis?", "option_a": "Congestive Heart Failure", "option_b": "Superior Vena Cava (SVC) Syndrome", "option_c": "Pericardial Tamponade", "option_d": "Anaphylaxis", "correct_answer": "B", "explanation": "SVC syndrome is most commonly caused by a lung malignancy compressing the SVC, leading to facial plethora and upper extremity venous congestion."},
  {"question": "A 22-year-old male presents with periorbital edema and cola-colored urine 2 weeks after a skin infection. Diagnosis?", "option_a": "Minimal Change Disease", "option_b": "Post-Streptococcal Glomerulonephritis", "option_c": "IgA Nephropathy", "option_d": "Goodpasture Syndrome", "correct_answer": "B", "explanation": "PSGN presents as a nephritic syndrome (hematuria, edema, hypertension) following a strep infection of the throat or skin."},
  {"question": "Which of the following is the most common cause of Nephrotic Syndrome in adults?", "option_a": "Minimal Change Disease", "option_b": "Focal Segmental Glomerulosclerosis (FSGS)", "option_c": "Post-streptococcal glomerulonephritis", "option_d": "IgA Nephropathy", "correct_answer": "B", "explanation": "FSGS is currently the most common primary cause of nephrotic syndrome in adults, particularly in African Americans."},
  {"question": "A patient with Vitamin B12 deficiency presents with anemia. What is the most likely finding on the peripheral blood smear?", "option_a": "Microcytic RBCs", "option_b": "Hypersegmented neutrophils and macro-ovalocytes", "option_c": "Schistocytes", "option_d": "Acanthocytes", "correct_answer": "B", "explanation": "Vitamin B12 and folate deficiencies cause megaloblastic anemia, characterized by large RBCs and neutrophils with more than 5 lobes."},
  {"question": "A 30-year-old female presents with fatigue and a butterfly rash. Lab shows positive anti-dsDNA. Diagnosis?", "option_a": "Dermatomyositis", "option_b": "Systemic Lupus Erythematosus (SLE)", "option_c": "Rosacea", "option_d": "Scleroderma", "correct_answer": "B", "explanation": "SLE is a systemic autoimmune disease characterized by multisystem involvement and specific antibodies like anti-dsDNA and anti-Smith."},
  {"question": "What is the primary diagnostic test for a patient with suspected Chronic Kidney Disease?", "option_a": "Urine Culture", "option_b": "Estimated GFR and Urine Albumin-to-Creatinine Ratio", "option_c": "Renal Biopsy", "option_d": "Renal Angiography", "correct_answer": "B", "explanation": "CKD is defined and staged based on GFR (<60 mL/min for >3 months) and markers of kidney damage (like albuminuria)."},
  {"question": "A patient presents with tearing chest pain radiating to the back and a blood pressure of 190/110. A Chest X-ray shows a widened mediastinum. Diagnosis?", "option_a": "Myocardial Infarction", "option_b": "Aortic Dissection", "option_c": "Esophageal Rupture", "option_d": "Tension Pneumothorax", "correct_answer": "B", "explanation": "Aortic dissection is a life-threatening emergency presenting with severe tearing pain and a widened mediastinum on imaging."},
  {"question": "Which heart valve is most commonly affected in Acute Rheumatic Carditis?", "option_a": "Aortic valve", "option_b": "Mitral valve", "option_c": "Tricuspid valve", "option_d": "Pulmonic valve", "correct_answer": "B", "explanation": "The mitral valve is involved in nearly all cases of chronic rheumatic heart disease, often resulting in stenosis."},
  {"question": "A 45-year-old male presents with severe pain in his first toe joint. Arthrocentesis shows needle-shaped, negatively birefringent crystals. Diagnosis?", "option_a": "Pseudogout", "option_b": "Gout", "option_c": "Septic Arthritis", "option_d": "Rheumatoid Arthritis", "correct_answer": "B", "explanation": "Negatively birefringent urate crystals are diagnostic for gouty arthritis."},
  {"question": "A patient with cirrhosis has increased abdominal girth. Paracentesis shows a SAAG of 1.2 g/dL. What does this indicate?", "option_a": "Malignancy", "option_b": "Portal Hypertension", "option_c": "Tuberculosis", "option_d": "Nephrotic syndrome", "correct_answer": "B", "explanation": "A Serum-Ascites Albumin Gradient (SAAG) >= 1.1 indicates that portal hypertension is the likely cause of ascites."},
  {"question": "Which of the following is the treatment of choice for an acute asthma exacerbation?", "option_a": "Inhaled Corticosteroids", "option_b": "Inhaled Short-Acting Beta-Agonists (SABA)", "option_c": "Oral Theophylline", "option_d": "Long-Acting Beta-Agonists (LABA)", "correct_answer": "B", "explanation": "SABAs like Albuterol provide rapid relief of bronchospasm during an acute attack."},
  {"question": "A 65-year-old male smoker has hematuria and a 5-cm renal mass on CT. What is the most likely diagnosis?", "option_a": "Wilms Tumor", "option_b": "Renal Cell Carcinoma", "option_c": "Renal Abscess", "option_d": "Angiomyolipoma", "correct_answer": "B", "explanation": "RCC is the most common primary renal malignancy in adults, frequently associated with smoking."},
  {"question": "Which of the following is a classic finding in Hemophilia A?", "option_a": "Low Platelet count", "option_b": "Prolonged aPTT, Normal PT", "option_c": "Prolonged PT, Normal aPTT", "option_d": "Prolonged Bleeding Time", "correct_answer": "B", "explanation": "Hemophilia A involves a deficiency of Factor VIII, which is part of the intrinsic pathway, thus prolonging the aPTT."},
  {"question": "A patient with suspected SIADH (Syndrome of Inappropriate ADH) will show which of the following?", "option_a": "Hypernatremia and dilute urine", "option_b": "Hyponatremia and concentrated urine", "option_c": "Hypokalemia and hypertension", "option_d": "Hyperglycemia", "correct_answer": "B", "explanation": "SIADH causes water retention, leading to dilutional hyponatremia and inappropriately high urine osmolality."},
  {"question": "A 50-year-old woman presents with dry eyes, dry mouth, and positive anti-Ro (SSA) antibodies. Diagnosis?", "option_a": "Sjogren's Syndrome", "option_b": "Systemic Sclerosis", "option_c": "Rheumatoid Arthritis", "option_d": "Lupus", "correct_answer": "A", "explanation": "Sjogren's syndrome is an autoimmune condition targeting exocrine glands, causing sicca (dryness) symptoms."},
  {"question": "What is the primary treatment for a patient with symptomatic bradycardia and hypotension?", "option_a": "Amiodarone", "option_b": "Atropine", "option_c": "Beta-blocker", "option_d": "Adenosine", "correct_answer": "B", "explanation": "Atropine is the first-line pharmacologic treatment for symptomatic bradycardia."},
  {"question": "A 60-year-old patient presents with a smoker's cough and hypercalcemia. CT shows a central lung mass. Diagnosis?", "option_a": "Adenocarcinoma", "option_b": "Squamous Cell Carcinoma", "option_c": "Small Cell Carcinoma", "option_d": "Large Cell Carcinoma", "correct_answer": "B", "explanation": "Squamous cell lung cancer is associated with smoking and often produces PTHrP, leading to hypercalcemia."},
  {"question": "In a patient with Heart Failure, which medication class has been shown to improve survival (mortality benefit)?", "option_a": "Loop Diuretics", "option_b": "ACE Inhibitors and Beta-blockers", "option_c": "Calcium Channel Blockers", "option_d": "Digoxin", "correct_answer": "B", "explanation": "ACE inhibitors, ARBs, Beta-blockers, and Mineralocorticoid receptor antagonists (Spironolactone) are key therapies that improve survival in HF with reduced ejection fraction."},
  {"question": "A patient presents with fever, weight loss, and night sweats. Chest X-ray shows upper lobe cavitary lesions. Diagnosis?", "option_a": "Pneumococcal Pneumonia", "option_b": "Tuberculosis", "option_c": "Lung Abscess", "option_d": "Sarcoidosis", "correct_answer": "B", "explanation": "Reactivation TB classically presents with constitutional symptoms and cavitation in the apical/upper lobes of the lung."},
  {"question": "Which heart murmur is heard as a mid-diastolic rumble with an opening snap?", "option_a": "Aortic Regurgitation", "option_b": "Mitral Stenosis", "option_c": "Mitral Regurgitation", "option_d": "Aortic Stenosis", "correct_answer": "B", "explanation": "Mitral stenosis, most often caused by rheumatic heart disease, presents with these classic auscultatory findings."},
  {"question": "A 40-year-old male with chronic alcohol use presents with confusion, ataxia, and eye movement abnormalities. Which vitamin is deficient?", "option_a": "Vitamin B12", "option_b": "Vitamin B1 (Thiamine)", "option_c": "Vitamin C", "option_d": "Vitamin D", "correct_answer": "B", "explanation": "Wernicke Encephalopathy is caused by thiamine deficiency, common in chronic alcoholism."},
  {"question": "A patient presents with a rest tremor and bradykinesia. Diagnosis?", "option_a": "Multiple Sclerosis", "option_b": "Parkinson's Disease", "option_c": "Essential Tremor", "option_d": "Huntington's Disease", "correct_answer": "B", "explanation": "Parkinson's disease is characterized by the triad of rest tremor, bradykinesia, and rigidity."},
  {"question": "Which of the following is the most common cause of Acute Pancreatitis?", "option_a": "Hypertriglyceridemia", "option_b": "Gallstones and Alcohol", "option_c": "Infection", "option_d": "Trauma", "correct_answer": "B", "explanation": "Gallstones and heavy alcohol use account for the vast majority of acute pancreatitis cases."},
  {"question": "A 55-year-old male smoker has sudden, painless loss of vision in one eye (curtain coming down). Diagnosis?", "option_a": "Acute Glaucoma", "option_b": "Retinal Detachment", "option_c": "Central Retinal Artery Occlusion", "option_d": "Optic Neuritis", "correct_answer": "B", "explanation": "Painless vision loss described as a curtain is highly suggestive of retinal detachment or amaurosis fugax."},
  {"question": "A patient with Chronic Kidney Disease has high PTH and low Calcium. What is this called?", "option_a": "Primary hyperparathyroidism", "option_b": "Secondary hyperparathyroidism", "option_c": "Hypoparathyroidism", "option_d": "Pseudohypoparathyroidism", "correct_answer": "B", "explanation": "CKD leads to secondary hyperparathyroidism due to phosphate retention and low active Vitamin D levels."},
  {"question": "Which of the following is a classic symptom of Aortic Stenosis?", "option_a": "Palpitations", "option_b": "Syncope, Angina, and Dyspnea", "option_c": "Hemoptysis", "option_d": "Malar flush", "correct_answer": "B", "explanation": "The SAD triad (Syncope, Angina, Dyspnea) is characteristic of severe aortic stenosis."},
  {"question": "A patient with bronze skin and Diabetes has iron overload. Diagnosis?", "option_a": "Wilson's Disease", "option_b": "Hereditary Hemochromatosis", "option_c": "Addison's Disease", "option_d": "Pellagra", "correct_answer": "B", "explanation": "Hemochromatosis leads to excessive iron deposition in organs, causing cirrhosis, bronze skin, and diabetes."},
  {"question": "What is the goal of Evidence-Based Medicine (EBM)?", "option_a": "To reduce hospital costs", "option_b": "To integrate best research with clinical expertise and patient values", "option_c": "To use only randomized controlled trials", "option_d": "To replace doctor's intuition", "correct_answer": "B", "explanation": "EBM is the conscientious use of current best evidence in making decisions about the care of individual patients."}
]

COURSE_ID = "NVU_MD_Y3_S1_C24"

async def main():
    client = AsyncIOMotorClient(os.environ["MONGO_URL"])
    db = client[os.environ["DB_NAME"]]
    
    current_count = await db.mcq_questions.count_documents({"course_id": COURSE_ID})
    print(f"Current questions: {current_count}")
    
    questions_to_insert = []
    for q in questions_data:
        question_doc = {
            "question_id": f"q_{uuid.uuid4().hex[:12]}",
            "course_id": COURSE_ID,
            "question": q["question"],
            "option_a": q["option_a"],
            "option_b": q["option_b"],
            "option_c": q["option_c"],
            "option_d": q["option_d"],
            "correct_answer": q["correct_answer"],
            "explanation": q["explanation"],
            "created_at": datetime.now(timezone.utc).isoformat()
        }
        questions_to_insert.append(question_doc)
    
    result = await db.mcq_questions.insert_many(questions_to_insert)
    print(f"Inserted: {len(result.inserted_ids)} questions")
    
    new_count = await db.mcq_questions.count_documents({"course_id": COURSE_ID})
    await db.courses.update_one(
        {"external_id": COURSE_ID},
        {"$set": {"mcq_count": new_count, "mcq_verified": True}}
    )
    print(f"Total now: {new_count}")

if __name__ == "__main__":
    asyncio.run(main())
