import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
import os
import uuid
from datetime import datetime, timezone

questions_data = [
  {"question": "A 64-year-old male with a history of myocardial infarction presents with progressive shortness of breath and orthopnea. On exam, he has bilateral pulmonary crackles and a displaced apex beat. What is the most likely mechanism of his symptoms?", "option_a": "Right ventricular failure due to pulmonary hypertension", "option_b": "Decreased left ventricular ejection fraction leading to pulmonary venous congestion", "option_c": "Constrictive pericarditis", "option_d": "High-output heart failure", "correct_answer": "B", "explanation": "Orthopnea and pulmonary crackles are signs of left-sided heart failure (systolic dysfunction post-MI), which causes fluid to back up into the lungs."},
  {"question": "A 45-year-old female presents with dry eyes and a dry mouth (sicca symptoms). Lab tests reveal positive anti-Ro (SS-A) and anti-La (SS-B) antibodies. What is the most likely diagnosis?", "option_a": "Systemic Lupus Erythematosus", "option_b": "Sjogren's Syndrome", "option_c": "Rheumatoid Arthritis", "option_d": "Systemic Sclerosis", "correct_answer": "B", "explanation": "Sjogren's Syndrome is an autoimmune disorder characterized by lymphocytic infiltration of exocrine glands, commonly associated with anti-Ro and anti-La antibodies."},
  {"question": "A 75-year-old male is admitted for a hip fracture. On day 3, he becomes acutely short of breath and tachycardic. His D-dimer is elevated, and ECG shows an S1Q3T3 pattern. What is the definitive diagnostic step?", "option_a": "Troponin level", "option_b": "CT Pulmonary Angiography (CTPA)", "option_c": "Chest X-ray", "option_d": "Echocardiogram", "correct_answer": "B", "explanation": "In a post-surgical patient with acute dyspnea, tachycardia, and S1Q3T3 (classic but non-specific PE sign), CTPA is the gold standard to confirm Pulmonary Embolism."},
  {"question": "A 28-year-old male presents with hemoptysis and hematuria. Lab tests show positive anti-glomerular basement membrane (anti-GBM) antibodies. Which structure is targeted by these antibodies?", "option_a": "Type II collagen", "option_b": "Type IV collagen", "option_c": "Albumin", "option_d": "Podocytes", "correct_answer": "B", "explanation": "Goodpasture Syndrome involves antibodies against the alpha-3 chain of Type IV collagen, found in both glomerular and alveolar basement membranes."},
  {"question": "A patient is found to have a serum potassium of 2.8 mEq/L. Which of the following ECG changes is most characteristic of hypokalemia?", "option_a": "Peaked T waves", "option_b": "Presence of U waves and ST-segment depression", "option_c": "Shortened QT interval", "option_d": "Delta waves", "correct_answer": "B", "explanation": "Hypokalemia typically presents with flattening of T waves, ST depression, and the appearance of U waves (prominent waves following the T wave)."},
  {"question": "A 50-year-old male with long-standing cirrhosis develops sudden abdominal pain and fever. Paracentesis shows an absolute neutrophil count (ANC) of 300 cells/mm3. What is the most likely diagnosis?", "option_a": "Acute Pancreatitis", "option_b": "Spontaneous Bacterial Peritonitis (SBP)", "option_c": "Bowel perforation", "option_d": "Hepatocellular carcinoma", "correct_answer": "B", "explanation": "SBP is diagnosed in cirrhotic patients with ascites when the ascitic fluid polymorphonuclear (PMN) cell count is >= 250 cells/mm3."},
  {"question": "A 35-year-old female presents with episodic headaches, palpitations, and diaphoresis. Her blood pressure is 190/110 mmHg. Which metabolite should be measured in a 24-hour urine collection?", "option_a": "5-HIAA", "option_b": "Metanephrines and Catecholamines", "option_c": "Cortisol", "option_d": "Aldosterone", "correct_answer": "B", "explanation": "The triad of headache, sweating, and tachycardia with hypertension is highly suggestive of Pheochromocytoma, which secretes metanephrines."},
  {"question": "Which of the following findings is most characteristic of Intravascular Hemolysis?", "option_a": "Increased haptoglobin", "option_b": "Decreased haptoglobin and presence of schistocytes", "option_c": "Decreased indirect bilirubin", "option_d": "Negative direct Coombs test", "correct_answer": "B", "explanation": "Free hemoglobin binds haptoglobin, causing haptoglobin levels to drop. Schistocytes (fragmented RBCs) are seen in microangiopathic hemolytic anemia."},
  {"question": "A 60-year-old male presents with painless gross hematuria. He has a 40-pack-year smoking history. What is the most likely diagnosis?", "option_a": "Nephrolithiasis", "option_b": "Bladder Cancer (Urothelial Carcinoma)", "option_c": "Benign Prostatic Hyperplasia", "option_d": "Polycystic Kidney Disease", "correct_answer": "B", "explanation": "Painless gross hematuria in an older smoker is bladder cancer until proven otherwise. Smoking is the most significant risk factor."},
  {"question": "A 52-year-old male with Type 2 Diabetes presents with a foot ulcer. He has decreased sensation in a stocking-glove distribution. What is the primary underlying cause?", "option_a": "Arterial occlusion", "option_b": "Distal symmetric polyneuropathy", "option_c": "Venous insufficiency", "option_d": "Vitamin B12 deficiency", "correct_answer": "B", "explanation": "Chronic hyperglycemia leads to nerve damage, typically starting in the longest nerves (feet), presenting as stocking-glove sensory loss."},
  {"question": "A 40-year-old female presents with unintentional weight loss, diarrhea, and skin hyperpigmentation. Labs show hyponatremia and hyperkalemia. Which test is used to confirm the diagnosis?", "option_a": "Dexamethasone suppression test", "option_b": "ACTH stimulation test", "option_c": "Oral glucose tolerance test", "option_d": "Water deprivation test", "correct_answer": "B", "explanation": "Primary Adrenal Insufficiency (Addison's) is confirmed by a lack of cortisol rise after administration of synthetic ACTH (Cosyntropin)."},
  {"question": "A 22-year-old male with Asthma presents to the ER with severe wheezing and is unable to speak in full sentences. His breath sounds are barely audible (silent chest). What is the next best step?", "option_a": "Administer inhaled corticosteroids", "option_b": "Immediate nebulized albuterol, ipratropium, and IV steroids", "option_c": "Obtain an urgent chest X-ray", "option_d": "Discharge with a spacer", "correct_answer": "B", "explanation": "A silent chest indicates critical airway obstruction. Urgent bronchodilators and systemic steroids are mandatory to prevent respiratory failure."},
  {"question": "Which of the following is the most common cause of an embolic stroke in a patient with no known carotid disease?", "option_a": "Ventricular septal defect", "option_b": "Atrial Fibrillation", "option_c": "Mitral valve prolapse", "option_d": "Aortic dissection", "correct_answer": "B", "explanation": "AFib leads to blood stasis in the left atrial appendage, forming clots that can embolize to the brain."},
  {"question": "A 66-year-old male with heavy alcohol use presents with confusion, ataxia, and ophthalmoplegia. Which vitamin deficiency is responsible?", "option_a": "Vitamin B12 (Cobalamin)", "option_b": "Vitamin B1 (Thiamine)", "option_c": "Vitamin B3 (Niacin)", "option_d": "Vitamin B6 (Pyridoxine)", "correct_answer": "B", "explanation": "Wernicke Encephalopathy presents with this classic triad due to thiamine deficiency, often secondary to chronic alcoholism."},
  {"question": "A 55-year-old female presents with symmetrical joint pain in her hands, sparing the distal interphalangeal (DIP) joints. She has morning stiffness lasting >1 hour. What is the most likely diagnosis?", "option_a": "Osteoarthritis", "option_b": "Rheumatoid Arthritis", "option_c": "Psoriatic Arthritis", "option_d": "Septic Arthritis", "correct_answer": "B", "explanation": "Rheumatoid Arthritis typically affects small joints symmetrically, causes prolonged morning stiffness, and classically spares the DIP joints."},
  {"question": "What is the most common cause of Acute Kidney Injury (AKI) in the hospital setting?", "option_a": "Glomerulonephritis", "option_b": "Acute Tubular Necrosis (ATN)", "option_c": "Ureteral stones", "option_d": "Vasculitis", "correct_answer": "B", "explanation": "ATN, often caused by ischemia or nephrotoxins (contrast, antibiotics), is the most frequent cause of intrinsic AKI in hospitalized patients."},
  {"question": "A 48-year-old male presents with epigastric pain that is relieved by eating. Endoscopy reveals a solitary ulcer in the proximal duodenum. Which factor is most commonly associated with this condition?", "option_a": "Zollinger-Ellison syndrome", "option_b": "Helicobacter pylori infection", "option_c": "Chronic steroid use", "option_d": "Gastroesophageal reflux", "correct_answer": "B", "explanation": "H. pylori is present in over 90% of patients with duodenal ulcers."},
  {"question": "A 60-year-old female with a history of breast cancer presents with severe back pain and hypercalcemia. What is the most likely mechanism of the hypercalcemia?", "option_a": "Increased intestinal absorption of calcium", "option_b": "Bone resorption due to metastatic disease", "option_c": "Excessive Vitamin D production", "option_d": "Hyperparathyroidism", "correct_answer": "B", "explanation": "Malignancy causes hypercalcemia either through direct bone destruction (metastases) or production of PTHrP."},
  {"question": "A 30-year-old patient presents with fever, weight loss, and night sweats. Exam shows painless lymphadenopathy in the neck. Biopsy shows Reed-Sternberg cells. Diagnosis?", "option_a": "Non-Hodgkin Lymphoma", "option_b": "Hodgkin Lymphoma", "option_c": "Sarcoidosis", "option_d": "Tuberculosis", "correct_answer": "B", "explanation": "Reed-Sternberg cells (owl's eye appearance) are the pathognomonic finding in Hodgkin Lymphoma."},
  {"question": "A 58-year-old male with hypertension and hyperlipidemia presents with sudden, painless loss of vision in one eye (like a curtain coming down). Exam shows a pale retina and a cherry-red spot at the macula. Diagnosis?", "option_a": "Retinal detachment", "option_b": "Central Retinal Artery Occlusion (CRAO)", "option_c": "Central Retinal Vein Occlusion (CRVO)", "option_d": "Acute angle-closure glaucoma", "correct_answer": "B", "explanation": "CRAO is an ocular emergency. The cherry-red spot occurs because the macula receives blood from the ciliary artery, unlike the rest of the pale, ischemic retina."},
  {"question": "A 50-year-old male presents with hemoptysis, weight loss, and chronic sinusitis. Lab shows positive c-ANCA (PR3-ANCA). Which of the following organs are most likely involved?", "option_a": "Heart and Liver", "option_b": "Lungs and Kidneys", "option_c": "Skin and Joints", "option_d": "Brain and Eyes", "correct_answer": "B", "explanation": "Granulomatosis with Polyangiitis (Wegener's) typically affects the upper/lower respiratory tract and the kidneys."},
  {"question": "Which of the following is the hallmark of restrictive lung disease on pulmonary function tests?", "option_a": "FEV1/FVC ratio < 0.7", "option_b": "Decreased Total Lung Capacity (TLC)", "option_c": "Increased Residual Volume (RV)", "option_d": "Normal DLCO", "correct_answer": "B", "explanation": "Restrictive diseases (like pulmonary fibrosis) are defined by reduced lung volumes (TLC), whereas the FEV1/FVC ratio remains normal or increased."},
  {"question": "A 70-year-old smoker presents with a 2-cm lung nodule on routine CXR. What is the most appropriate next step?", "option_a": "Surgical resection", "option_b": "Comparison with previous imaging and Chest CT", "option_c": "Observation for 1 year", "option_d": "Broad-spectrum antibiotics", "correct_answer": "B", "explanation": "The first step in evaluating a solitary pulmonary nodule is assessing stability by looking at old films, followed by a high-resolution CT."},
  {"question": "A 45-year-old male with a history of chronic kidney disease presents with a pericardial friction rub on exam. What is the most likely cause?", "option_a": "Viral infection", "option_b": "Uremia", "option_c": "Post-MI syndrome (Dressler)", "option_d": "Systemic Lupus Erythematosus", "correct_answer": "B", "explanation": "Uremic pericarditis is a common complication of advanced CKD and is an absolute indication for starting dialysis."},
  {"question": "What is the primary treatment for a patient with symptomatic bradycardia (Heart rate 35 bpm) and hemodynamic instability?", "option_a": "Beta-blockers", "option_b": "Atropine", "option_c": "Adenosine", "option_d": "Amiodarone", "correct_answer": "B", "explanation": "Atropine is the first-line pharmacologic treatment for symptomatic bradycardia."},
  {"question": "A 32-year-old female presents with fatigue and a butterfly rash on her face. Lab tests show positive anti-dsDNA antibodies. What is the most likely diagnosis?", "option_a": "Dermatomyositis", "option_b": "Systemic Lupus Erythematosus (SLE)", "option_c": "Scleroderma", "option_d": "Rosacea", "correct_answer": "B", "explanation": "Anti-dsDNA and anti-Smith antibodies are highly specific for SLE."},
  {"question": "A 55-year-old male presents with difficulty swallowing solids and liquids. Manometry shows bird-beak appearance and failure of the lower esophageal sphincter (LES) to relax. Diagnosis?", "option_a": "Esophageal cancer", "option_b": "Achalasia", "option_c": "Diffuse esophageal spasm", "option_d": "Hiatal hernia", "correct_answer": "B", "explanation": "Achalasia is a motility disorder where the LES fails to relax due to loss of inhibitory neurons in the myenteric plexus."},
  {"question": "In a patient with Chronic Kidney Disease, secondary hyperparathyroidism occurs primarily due to:", "option_a": "Hypercalcemia", "option_b": "Phosphate retention and decreased 1,25-dihydroxyvitamin D", "option_c": "Primary parathyroid adenoma", "option_d": "Hypomagnesemia", "correct_answer": "B", "explanation": "CKD causes phosphate retention and low active Vitamin D, both of which trigger the parathyroid glands to release more PTH (secondary hyperparathyroidism)."},
  {"question": "A 60-year-old male presents with an enlarged left supraclavicular lymph node (Virchow's node). This finding is classically associated with:", "option_a": "Lung cancer", "option_b": "Gastric adenocarcinoma", "option_c": "Thyroid cancer", "option_d": "Melanoma", "correct_answer": "B", "explanation": "Virchow's node is a classic sign of metastatic abdominal malignancy, particularly gastric cancer."},
  {"question": "A 40-year-old female presents with weight gain, dry skin, and cold intolerance. Her TSH is 15 mIU/L (High). What is the next best step?", "option_a": "Thyroid ultrasound", "option_b": "Start Levothyroxine", "option_c": "Radioactive iodine uptake scan", "option_d": "Brain MRI", "correct_answer": "B", "explanation": "An elevated TSH with symptoms of hypothyroidism is diagnostic of primary hypothyroidism (most commonly Hashimoto's) and warrants hormone replacement."},
  {"question": "Which heart murmur is typically loudest at the apex and radiates to the left axilla?", "option_a": "Aortic Stenosis", "option_b": "Mitral Regurgitation", "option_c": "Mitral Stenosis", "option_d": "Aortic Regurgitation", "correct_answer": "B", "explanation": "Mitral Regurgitation presents as a holosystolic murmur at the apex radiating to the axilla."},
  {"question": "A 65-year-old male with a history of HTN and AFib presents with acute, severe abdominal pain that is out of proportion to physical exam. Diagnosis?", "option_a": "Acute Cholecystitis", "option_b": "Acute Mesenteric Ischemia", "option_c": "Appendicitis", "option_d": "Biliary Colic", "correct_answer": "B", "explanation": "This classic description in an elderly patient with AFib suggests an embolic occlusion of the mesenteric arteries."},
  {"question": "Which of the following is a classic clinical finding in Multiple Sclerosis?", "option_a": "Resting tremor", "option_b": "Optic neuritis and internuclear ophthalmoplegia", "option_c": "Symmetrical ascending paralysis", "option_d": "Muscle fasciculations", "correct_answer": "B", "explanation": "MS is a demyelinating disease of the CNS, often presenting with vision changes (optic neuritis) and brainstem signs like INO."},
  {"question": "A 50-year-old male presents with headache and plethoric (red) face. Labs show Hematocrit of 60% and low Erythropoietin (EPO). What is the likely diagnosis?", "option_a": "Dehydration", "option_b": "Polycythemia Vera", "option_c": "Renal cell carcinoma", "option_d": "Chronic hypoxia", "correct_answer": "B", "explanation": "Polycythemia Vera is a myeloproliferative disorder (JAK2 mutation) characterized by autonomous RBC production, leading to low EPO."},
  {"question": "A 72-year-old male with CKD and HTN presents with sudden leg weakness. Lab shows Potassium of 6.8 mEq/L. Which medication is most likely to have contributed?", "option_a": "Hydrochlorothiazide", "option_b": "Lisinopril (ACE inhibitor)", "option_c": "Amlodipine", "option_d": "Furosemide", "correct_answer": "B", "explanation": "ACE inhibitors and ARBs decrease aldosterone effects, causing potassium retention, especially in patients with existing renal impairment."},
  {"question": "In a patient with suspected primary hyperaldosteronism (Conn's Syndrome), which lab findings are expected?", "option_a": "Hypertension and hyperkalemia", "option_b": "Hypertension, hypokalemia, and low plasma renin", "option_c": "Hypotension and hyperkalemia", "option_d": "Hypertension, hyperkalemia, and high plasma renin", "correct_answer": "B", "explanation": "Aldosterone causes Na+ retention (hypertension) and K+ wasting (hypokalemia). The high blood pressure feedback suppresses renin production."},
  {"question": "A 40-year-old male with Type 1 Diabetes is brought to the ER confused and vomiting. His breath smells fruity, and his blood sugar is 450 mg/dL. What is the acid-base disturbance?", "option_a": "Metabolic Alkalosis", "option_b": "High Anion Gap Metabolic Acidosis", "option_c": "Respiratory Acidosis", "option_d": "Normal Anion Gap Metabolic Acidosis", "correct_answer": "B", "explanation": "Diabetic Ketoacidosis (DKA) produces ketoacids, which consume bicarbonate and create an increased anion gap."},
  {"question": "A 55-year-old male presents with fatigue and easy bruising. Smear shows Auer rods in the cytoplasm of blasts. Diagnosis?", "option_a": "Acute Lymphoblastic Leukemia (ALL)", "option_b": "Acute Myeloid Leukemia (AML)", "option_c": "Chronic Myeloid Leukemia (CML)", "option_d": "Chronic Lymphocytic Leukemia (CLL)", "correct_answer": "B", "explanation": "Auer rods are eosinophilic needle-like inclusions pathognomonic for AML (especially M3 subtype)."},
  {"question": "What is the clinical triad of Normal Pressure Hydrocephalus (NPH)?", "option_a": "Headache, vomiting, papilledema", "option_b": "Dementia, Gait instability, Urinary incontinence", "option_c": "Tremor, Rigidity, Bradykinesia", "option_d": "Fever, neck stiffness, altered mental status", "correct_answer": "B", "explanation": "Commonly remembered as Wet, Wobbly, and Wacky."},
  {"question": "A 60-year-old patient with pneumonia has a pH of 7.25 and PaCO2 of 55 mmHg. What is the primary acid-base disorder?", "option_a": "Metabolic Acidosis", "option_b": "Respiratory Acidosis", "option_c": "Respiratory Alkalosis", "option_d": "Metabolic Alkalosis", "correct_answer": "B", "explanation": "The low pH indicates acidosis, and the high CO2 (alveolar hypoventilation) is the cause."},
  {"question": "A 30-year-old male presents with hemoptysis and weight loss. Chest X-ray shows upper lobe cavitary lesions. What is the most likely infectious cause?", "option_a": "Streptococcus pneumoniae", "option_b": "Mycobacterium tuberculosis", "option_c": "Mycoplasma pneumoniae", "option_d": "Influenza virus", "correct_answer": "B", "explanation": "Upper lobe cavitary disease in a patient with constitutional symptoms is the classic presentation of reactivation Tuberculosis."},
  {"question": "Which of the following is a classic finding in Hemophilia A?", "option_a": "Low platelet count", "option_b": "Prolonged PTT and normal PT/Bleeding time", "option_c": "Prolonged PT and normal PTT", "option_d": "Prolonged Bleeding Time", "correct_answer": "B", "explanation": "Hemophilia A is a deficiency of Factor VIII (intrinsic pathway), so the PTT is prolonged while other tests remain normal."},
  {"question": "A 65-year-old male presents with lower back pain and elevated alkaline phosphatase. Prostate exam is concerning. Bone scan shows multiple osteoblastic lesions. Diagnosis?", "option_a": "Multiple Myeloma", "option_b": "Metastatic Prostate Cancer", "option_c": "Osteoporosis", "option_d": "Paget's Disease of Bone", "correct_answer": "B", "explanation": "Prostate cancer classically metastasizes to bone, creating sclerotic (osteoblastic) lesions on imaging."},
  {"question": "A patient with mitral stenosis is at significantly increased risk for which of the following?", "option_a": "Aortic dissection", "option_b": "Atrial Fibrillation and systemic emboli", "option_c": "Ventricular septal defect", "option_d": "Coarctation of the aorta", "correct_answer": "B", "explanation": "Mitral stenosis leads to left atrial enlargement, which triggers AFib and clot formation."},
  {"question": "A 40-year-old male presents with severe crushing chest pain. ECG shows ST-segment depression in V1-V3 and tall R waves. What does this represent?", "option_a": "Normal variant", "option_b": "Posterior Wall Myocardial Infarction", "option_c": "Right ventricular hypertrophy", "option_d": "Pulmonary Embolism", "correct_answer": "B", "explanation": "Depression in anterior leads (V1-V3) is often the mirror image of ST elevation in a posterior MI."},
  {"question": "Which of the following is the most common cause of hyperthyroidism in the elderly?", "option_a": "Graves' disease", "option_b": "Toxic Multinodular Goiter", "option_c": "Hashimoto's thyroiditis", "option_d": "Iatrogenic overdose", "correct_answer": "B", "explanation": "While Graves' is common overall, elderly patients more frequently develop hyperthyroidism from toxic nodules."},
  {"question": "A 55-year-old male smoker presents with painless gross hematuria. CT shows a solid mass on the upper pole of the right kidney. Diagnosis?", "option_a": "Renal Abscess", "option_b": "Renal Cell Carcinoma", "option_c": "Ureteral stone", "option_d": "Angiomyolipoma", "correct_answer": "B", "explanation": "RCC often presents with hematuria, flank pain, and a palpable mass (the classic triad, though rare in full)."},
  {"question": "A 50-year-old female presents with chronic pruritus, fatigue, and positive anti-mitochondrial antibodies (AMA). What is the likely diagnosis?", "option_a": "Primary Biliary Cholangitis (PBC)", "option_b": "Primary Sclerosing Cholangitis (PSC)", "option_c": "Autoimmune Hepatitis", "option_d": "Wilson's Disease", "correct_answer": "A", "explanation": "PBC is an autoimmune destruction of small intrahepatic bile ducts, classically seen in middle-aged women with positive AMA."},
  {"question": "A 25-year-old male presents with sudden onset of severe right-sided scrotal pain. Physical exam shows a high-riding testis and absent cremasteric reflex. Diagnosis?", "option_a": "Epididymitis", "option_b": "Testicular Torsion", "option_c": "Hydrocele", "option_d": "Testicular Cancer", "correct_answer": "B", "explanation": "Testicular torsion is a surgical emergency; the absent cremasteric reflex is a highly sensitive finding."},
  {"question": "Which of the following describes Pulsus Paradoxus?", "option_a": "Variation in heart rate with breathing", "option_b": "Drop in systolic blood pressure > 10 mmHg during inspiration", "option_c": "Irregular heart rhythm", "option_d": "Weak peripheral pulses", "correct_answer": "B", "explanation": "Pulsus paradoxus is a classic finding in cardiac tamponade and severe asthma/COPD."}
]

COURSE_ID = "NVU_MD_Y3_S1_C24"

async def main():
    client = AsyncIOMotorClient(os.environ["MONGO_URL"])
    db = client[os.environ["DB_NAME"]]
    
    current_count = await db.mcq_questions.count_documents({"course_id": COURSE_ID})
    print(f"Current questions: {current_count}")
    
    questions_to_insert = []
    for q in questions_data:
        question_doc = {
            "question_id": f"q_{uuid.uuid4().hex[:12]}",
            "course_id": COURSE_ID,
            "question": q["question"],
            "option_a": q["option_a"],
            "option_b": q["option_b"],
            "option_c": q["option_c"],
            "option_d": q["option_d"],
            "correct_answer": q["correct_answer"],
            "explanation": q["explanation"],
            "created_at": datetime.now(timezone.utc).isoformat()
        }
        questions_to_insert.append(question_doc)
    
    result = await db.mcq_questions.insert_many(questions_to_insert)
    print(f"Inserted: {len(result.inserted_ids)} questions")
    
    new_count = await db.mcq_questions.count_documents({"course_id": COURSE_ID})
    await db.courses.update_one(
        {"external_id": COURSE_ID},
        {"$set": {"mcq_count": new_count, "mcq_verified": True}}
    )
    print(f"Total now: {new_count}")

if __name__ == "__main__":
    asyncio.run(main())
